# -*- coding: utf-8 -*-
### mapping for all possible channels on earth :)

channels_map = {
  "БНТ 1":{"id":"BNT1","group":"Национални","logo":"http://logos.kodibg.org/bnt1.png"},
  "bTV":{"id": "bTV","group":"Национални","logo": "http://logos.kodibg.org/btv.png"},
  "Nova":{"id": "Nova","group":"Национални","logo": "http://logos.kodibg.org/novatv.png"},
  "Nova TV":{"id": "Nova","group":"Национални","logo": "http://logos.kodibg.org/novatv.png"},
  "bTV Comedy":{"id":"bTVComedy", "group":"Филми","logo":"http://logos.kodibg.org/btvcomedy.png"},
  "bTV Cinema":{"id":"bTVCinema", "group":"Филми","logo":"http://logos.kodibg.org/btvcinema.png"},
  "bTV Action":{"id":"bTVAction", "group":"Филми","logo":"http://logos.kodibg.org/btvaction.png"},
  "KinoNova":{"id":"KinoNova", "group":"Филми","logo":"http://logos.kodibg.org/kinonova.png"},
  "Diema":{"id":"Diema", "group":"Филми","logo":"http://logos.kodibg.org/diema.png"},
  "FOX Life":{"id":"FOXLife", "group":"Филми","logo":"http://logos.kodibg.org/foxlife.png"},
  "FOX Crime":{"id":"FOXCrime", "group":"Филми","logo":"http://logos.kodibg.org/foxcrime.png"},
  "FOX Channel":{"id":"FOXChannel", "group":"Филми","logo":"http://logos.kodibg.org/fox.png"},
  "BNT World":{"id":"BNTWorld", "group":"Национални","logo":"http://logos.kodibg.org/bntworld.png"},
  "БНТ 2":{"id":"БНТ 2", "group":"Национални","logo":"http://logos.kodibg.org/bnt2.png"},
  "Diema Family":{"id":"DiemaFamily", "group":"Филми","logo":"http://logos.kodibg.org/diemafamily.png"},
  "TV 1000":{"id":"TV1000", "group":"Филми","logo":"http://logos.kodibg.org/tv1000.png"},
  "DIVA Universal":{"id":"DIVA Universal", "group":"Национални","logo":"http://logos.kodibg.org/diva.png"},
  "AXN":{"id":"AXN", "group":"Филми","logo":"http://logos.kodibg.org/axn.png"},
  "AXN White":{"id":"AXNWhite", "group":"Филми","logo":"http://logos.kodibg.org/axnwhite.png"},
  "AXN Black":{"id":"AXNBlack", "group":"Филми","logo":"http://logos.kodibg.org/axnblack.png"},
  "Bulgaria on Air":{"id":"BulgariaOnAir", "group":"Национални","logo":"http://logos.kodibg.org/bgonair.png"},
  "BIT":{"id":"BiT", "group":"Национални","logo":"http://logos.kodibg.org/bit.png"},
  "BIT HD":{"id":"BiT", "group":"Национални","logo":"http://logos.kodibg.org/bit.png"},
  "ТВ Европа":{"id":"tveurope", "group":"Национални","logo":"http://logos.kodibg.org/tveuropa.png"},
  "Канал 3":{"id":"kanal3", "group":"Национални","logo":"http://logos.kodibg.org/kanal3.png"},
  "СКАТ":{"id":"Skat", "group":"Национални","logo":"http://logos.kodibg.org/skat.png"},
  "HMTV":{"id":"hmtv", "group":"Филми","logo":"http://logos.kodibg.org/hmtv.png"},
  "AMC":{"id":"AMC", "group":"Филми","logo":"http://logos.kodibg.org/amc.png"},
  "БНТ HD в SD":{"id":"BNTHD", "group":"Спортни","logo":"http://logos.kodibg.org/bnthd.png"},
  "БНТ HD":{"id":"BNTHD", "group":"Спортни","logo":"http://logos.kodibg.org/bnthd.png"},
  "BNT1 HD":{"id":"BNT1", "group":"Национални","logo":"http://logos.kodibg.org/bnt1.png"},
  "БНТ 1 HD":{"id":"BNT1", "group":"Национални","logo":"http://logos.kodibg.org/bnt1.png"},
  "bTV HD":{"id":"bTV", "group":"Национални","logo":"http://logos.kodibg.org/btv.png"},
  "bTV Action HD":{"id":"bTVAction", "group":"Филми","logo":"http://logos.kodibg.org/btvaction.png"},
  "Bloomberg BG HD":{"id":"Bloomberg", "group":"Национални","logo":"http://logos.kodibg.org/bloombergtvbulgaria.png"},
  "FOX HD":{"id":"FOX", "group":"Филми","logo":"http://logos.kodibg.org/fox.png"},
  "History Channel":{"id":"HistoryChannel", "group":"Документални","logo":"http://logos.kodibg.org/history.png"},
  "Viasat Explorer":{"id":"ViasatExplorer", "group":"Документални","logo":"http://logos.kodibg.org/viasatexplorer.png"},
  "Viasat History":{"id":"ViasatHistory", "group":"Документални","logo":"http://logos.kodibg.org/viasathistory.png"},
  "Viasat Nature":{"id":"ViasatNature", "group":"Документални","logo":"http://logos.kodibg.org/viasathistory.png"},
  "Animal Planet":{"id":"AnimalPlanet", "group":"Документални","logo":"http://logos.kodibg.org/animalplanet.png"},
  "Discovery Channel":{"id":"DiscoveryChannel", "group":"Документални","logo":"http://logos.kodibg.org/discovery.png"},
  "Discovery Science":{"id":"DiscoveryScience", "group":"Документални","logo":"http://logos.kodibg.org/discoveryscience.png"},
  "Science":{"id":"DiscoveryScience", "group":"Документални","logo":"http://logos.kodibg.org/discoveryscience.png"},
  "Discovery World":{"id":"DiscoveryWorld", "group":"Документални","logo":"http://logos.kodibg.org/discoveryworld.png"},
  "National Geographic":{"id":"National Geographic", "group":"Документални","logo":"http://logos.kodibg.org/natgeo.png"},
  "NGC HD":{"id":"NatGeo", "group":"Документални","logo":"http://logos.kodibg.org/natgeo.png"},
  "NatGeo HD":{"id":"NatGeo", "group":"Документални","logo":"http://logos.kodibg.org/natgeo.png"},
  "NatGeo Wild":{"id":"NatGeoWild", "group":"Документални","logo":"http://logos.kodibg.org/natgeowild.png"},
  "NatGeo Wild HD":{"id":"NatGeoWild", "group":"Документални","logo":"http://logos.kodibg.org/natgeowild.png"},
  "National Geogrphic WILD HD":{"id":"NatGeoWild", "group":"Документални","logo":"http://logos.kodibg.org/natgeowild.png"},
  "Viasat HD":{"id":"Viasat", "group":"Документални","logo":"http://logos.kodibg.org/viasathistory.png"},
  "Discovery HD":{"id":"DiscoveryHDShowcase", "group":"Документални","logo":"http://logos.kodibg.org/discoveryhdshowcase.png"},
  "History HD":{"id":"History", "group":"Документални","logo":"http://logos.kodibg.org/history.png"},
  "History Channel HD":{"id":"History", "group":"Документални","logo":"http://logos.kodibg.org/history.png"},
  "History 2 HD":{"id":"History2", "group":"Документални","logo":""},
  "Travel Channel HD":{"id":"TravelChannel", "group":"Документални","logo":"http://logos.kodibg.org/travelchannel.png"},
  "Travel Channel":{"id":"TravelChannel", "group":"Документални","logo":"http://logos.kodibg.org/travelchannel.png"},
  "Travel HD":{"id":"TravelHD", "group":"Документални","logo":"http://logos.kodibg.org/traveltvhd.png"},
  "Travel TV HD":{"id":"TravelHD", "group":"Документални","logo":"http://logos.kodibg.org/traveltvhd.png"},
  "Travel TV":{"id":"TravelHD", "group":"Документални","logo":"http://logos.kodibg.org/traveltv.png"},
  "Travel HD в SD":{"id":"TravelHD", "group":"Документални","logo":"http://logos.kodibg.org/travelhd.png"},
  "TVT Tourism":{"id":"TVTTourism", "group":"Документални","logo":"http://logos.kodibg.org/tvt.png"},
  "От близо HD":{"id":"OtBlizoHD", "group":"Документални","logo":""},
  "DocuBox HD":{"id":"DocuBox", "group":"Документални","logo":"http://logos.kodibg.org/docubox.png"},
  "Wild TV HD":{"id":"WildTV", "group":"Документални","logo":""},
  "DTX":{"id":"DTX", "group":"Документални","logo":""},
  "C&I Networks":{"id":"vi", "group":"Документални","logo":"http://logos.kodibg.org/ci.png"},
  "Дестинация BG":{"id":"DestinationBG", "group":"Документални","logo":"http://logos.kodibg.org/destinationbg.png"},
  "Destination BG HD":{"id":"DestinationBG", "group":"Документални","logo":"http://logos.kodibg.org/destinationbg.png"},
  "Българска история HD":{"id":"BulHistory", "group":"Документални","logo":"http://logos.kodibg.org/bghistory.png"},
  "Hobby TV":{"id":"HobbyTV", "group":"Документални","logo":"http://logos.kodibg.org/hobbyhd.png"},
  "Hobby HD":{"id":"HobbyTVHD", "group":"Документални","logo":"http://logos.kodibg.org/hobbyhd.png"},
  "Hobby TV HD":{"id":"HobbyTVHD", "group":"Документални","logo":"http://logos.kodibg.org/hobbyhd.png"},
  "OutDoor HD":{"id":"OutDoor", "group":"Документални","logo":"http://logos.kodibg.org/outdoorchannel.png"},
  "BG Лов":{"id":"HobbyLovHD", "group":"Документални","logo":"http://logos.kodibg.org/hobbylov.png"},
  "Hobby lov HD":{"id":"HobbyLovHD", "group":"Документални","logo":"http://logos.kodibg.org/hobbylov.png"},
  "Animal Planet HD":{"id":"AnimalPlanet", "group":"Документални","logo":"http://logos.kodibg.org/animalplanet.png"},
  "Discovery Science HD":{"id":"DiscoveryScience", "group":"Документални","logo":"http://logos.kodibg.org/discoveryscience.png"},
  "Food Network":{"id":"FoodNetworkHD", "group":"Тематични","logo":"http://logos.kodibg.org/foodnetwork.png"},
  "Food Network HD":{"id":"FoodNetworkHD", "group":"Тематични","logo":"http://logos.kodibg.org/foodnetwork.png"},
  "Da Vinci Learning":{"id":"DaVinciLearning", "group":"Документални","logo":"http://logos.kodibg.org/davincilearning.png"},
  "The World":{"id":"TheWorld", "group":"Документални","logo":""},
  "Chasse & Peche":{"id":"ChassePeche", "group":"Документални","logo":""},
  "24 Техно":{"id":"24_techno", "group":"Документални","logo":""},
  "Wness HD":{"id":"Wness", "group":"Тематични","logo":""},
  "Spark":{"id":"Spark", "group":"Документални","logo":""},
  "ID Xtra":{"id":"IDXtra", "group":"Документални","logo":"http://logos.kodibg.org/investigationdiscoveryxtra.png"},
  "24 Kitchen HD":{"id":"24Kitchen", "group":"Тематични","logo":"http://logos.kodibg.org/24kitchen.png"},
  "Fine Living":{"id":"FineLiving", "group":"Тематични","logo":"http://logos.kodibg.org/finelivingnetwork.png"},
  "24 Kitchen":{"id":"24Kitchen", "group":"Тематични","logo":"http://logos.kodibg.org/24kitchen.png"},
  "Kitchen":{"id":"24Kitchen", "group":"Тематични","logo":"http://logos.kodibg.org/24kitchen.png"},
  "Fiesta":{"id":"Fiesta", "group":"Тематични","logo":"http://logos.kodibg.org/fiestatv.png"},
  "bTV Lady":{"id":"bTVLady", "group":"Филми","logo":"http://logos.kodibg.org/btvlady.png"},
  "TLC":{"id":"TLC", "group":"Филми","logo":"http://logos.kodibg.org/tlc.png"},
  "CBS Drama":{"id":"CBSDrama", "group":"Филми","logo":"http://logos.kodibg.org/cbsdrama.png"},
  "CBS Reality":{"id":"CBSReality", "group":"Филми","logo":"http://logos.kodibg.org/cbsreality.png"},
  "Comedy Central":{"id":"ComedyCentral", "group":"Филми","logo":"http://logos.kodibg.org/comedycentralextra.png"},
  "English Club":{"id":"EnglishClub", "group":"Национални","logo":""},
  "HBO 3":{"id":"HBO3", "group":"Национални","Филми":"http://logos.kodibg.org/tvbg/hbo3.png"},
  "Movie Star":{"id":"MovieStar", "group":"Филми","logo":"http://logos.kodibg.org/moviestar.png"},
  "HBO":{"id":"HBOHD", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo.png"},
  "HBO 2":{"id":"HBOComedy", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo.png2"},
  "Cinemax":{"id":"Cinemax", "group":"Филми","logo":"http://logos.kodibg.org/cinemax.png"},
  "Cinemax 2":{"id":"Cinemax2", "group":"Филми","logo":"http://logos.kodibg.org/cinemax2.png"},
  "HBO HD":{"id":"HBOHD", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo.png"},
  "HBO 2 HD":{"id":"HBOComedy", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo2.png"},
  "Cinemax HD":{"id":"Cinemax", "group":"Филми","logo":"http://logos.kodibg.org/cinemax.png"},
  "Cinemax 2 HD":{"id":"Cinemax2", "group":"Филми","logo":"http://logos.kodibg.org/cinemax2.png"},
  "HBO 3 HD":{"id":"HBO3", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo3.png"},
  "Первый канал (EUR)":{"id":"PerviyKanal", "group":"Руски","logo":"http://logos.kodibg.org/perviykanal.png"},
  "Первый канал HD (RU)":{"id":"PerviyKanal", "group":"Руски","logo":"http://logos.kodibg.org/perviykanal.png"},
  "CTC Инт.":{"id":"CTC Инт.", "group":"Руски","logo":""},
  "TVCI Центр":{"id":"TVCI Центр", "group":"Руски","logo":""},
  "ТНТ":{"id":"ТНТ", "group":"Руски","logo":""},
  "RTVi":{"id":"RTVi", "group":"Руски","logo":""},
  "Живи":{"id":"Живи", "group":"Руски","logo":""},
  "Охота и рыбалка":{"id":"Ribalka", "group":"Руски","logo":"http://logos.kodibg.org/ohotairybalka.png"},
  "Звезда +2":{"id":"Звезда +2", "group":"Руски","logo":""},
  "Россия HD":{"id":"Россия HD", "group":"Руски","logo":""},
  "TV RUS":{"id":"TV RUS", "group":"Руски","logo":""},
  "НТВ HD":{"id":"НТВ HD", "group":"Руски","logo":""},
  "Россия 24":{"id":"Россия 24", "group":"Руски","logo":""},
  "НТВ Мир":{"id":"НТВ Мир", "group":"Руски","logo":""},
  "Наше кино":{"id":"Наше кино", "group":"Руски","logo":""},
  "РТР Планета":{"id":"РТР Планета", "group":"Руски","logo":""},
  "Дом кино":{"id":"Дом кино", "group":"Руски","logo":""},
  "Время":{"id":"Время", "group":"Руски","logo":""},
  "Перец":{"id":"Перец", "group":"Руски","logo":""},
  "Телекафе":{"id":"Телекафе", "group":"Руски","logo":""},
  "Eurosport":{"id":"Eurosport", "group":"Спортни","logo":"http://logos.kodibg.org/eurosport.png"},
  "Eurosport 2":{"id":"Eurosport2", "group":"Спортни","logo":"http://logos.kodibg.org/eurosport2.png"},
  "Nova Sport":{"id":"NovaSport", "group":"Спортни","logo":"http://logos.kodibg.org/novasport.png"},
  "Sport+ HD":{"id":"SportPlusHD", "group":"Спортни","logo":"http://logos.kodibg.org/sportplushd.png"},
  "F+":{"id":"FPlus", "group":"Спортни","logo":"http://logos.kodibg.org/fplus.png"},
  "TV+":{"id":"TVPlus", "group":"Национални","logo":"http://logos.kodibg.org/tvplus.png"},
  "Eurosport HD":{"id":"Eurosport", "group":"Спортни","logo":"http://logos.kodibg.org/eurosport.png"},
  "Eurosport 2 HD":{"id":"Eurosport2", "group":"Спортни","logo":"http://logos.kodibg.org/eurosport2.png"},
  "RING BG HD":{"id":"RING", "group":"Спортни","logo":"http://logos.kodibg.org/ring.png"},
  "Ring HD":{"id":"RING", "group":"Спортни","logo":"http://logos.kodibg.org/ring.png"},
  "RING BG":{"id":"RING", "group":"Спортни","logo":"http://logos.kodibg.org/ring.png"},
  "Diema Sport":{"id":"DiemaSport", "group":"Спортни","logo":"http://logos.kodibg.org/diemasport.png"},
  "Eurosport News":{"id":"EurosportNews", "group":"Спортни","logo":""},
  "Sky Sport HD 1":{"id":"Sky Sport HD 1", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/de/thumb/6/6d/Sky_Sport_HD_1_off-air_2011.png/320px-Sky_Sport_HD_1_off-air_2011.png"},
  "Sky Sport HD 2":{"id":"Sky Sport HD 2", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/de/thumb/4/42/Sky_Sport_HD_2_off-air_2011.png/320px-Sky_Sport_HD_2_off-air_2011.png"},
  "Sky Sport Austria":{"id":"Sky Sport Austria", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Sky_Sport_Austria_Logo_2016.png/320px-Sky_Sport_Austria_Logo_2016.png"},
  "Sportal HD":{"id":"Sportaltv", "group":"Спортни","logo":"http://logos.kodibg.org/sportalbg.png"},
  "Diema Sport HD":{"id":"DiemaSport", "group":"Спортни","logo":"http://logos.kodibg.org/diemasport.png"},
  "Diema Sport 2 HD":{"id":"DiemaSport2", "group":"Спортни","logo":"http://logos.kodibg.org/diemasport2.png"},
  "Nova Sport HD":{"id":"NovaSport", "group":"Спортни","logo":"http://logos.kodibg.org/novasport.png"},
  "BT Sports 1 *":{"id":"BT Sports 1 *", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/6/68/BT_Sport_1_%28pre-launch%29.svg/revision/latest/scale-to-width-down/640?cb=20130806193244"},
  "BT Sports 2 *":{"id":"BT Sports 2 *", "group":"Спортни","logo":"http://vignette1.wikia.nocookie.net/logopedia/images/2/2c/BT_Sport_2_%28pre-launch%29.svg/revision/latest/scale-to-width-down/640?cb=20130806193300"},
  "Sky Sports F1":{"id":"Sky Sports F1", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/skysportsf1.png"},
  "Sky Sports 1":{"id":"Sky Sports 1", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/skysports1.png"},
  "Sky Sports 2":{"id":"Sky Sports 2", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/skysports2.png"},
  "Sky Sports 3":{"id":"Sky Sports 3", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/skysports3.png"},
  "Sky Sports 4":{"id":"Sky Sports 4", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/skysports4.png"},
  "Sky Sports 5":{"id":"Sky Sports 5", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/skysports5.png"},
  "RAI Sport 1":{"id":"RAI Sport 1", "group":"Спортни","logo":""},
  "RAI Sport 2":{"id":"RAI Sport 2", "group":"Спортни","logo":""},
  "Supper Tennis HD":{"id":"Supper Tennis HD", "group":"Спортни","logo":""},
  "Deutsche Welle":{"id":"Deutsche Welle", "group":"Новини","logo":"http://logos.kodibg.org/deutschewelle.png"},
  "CNN International":{"id":"CNNInternational", "group":"Новини","logo":"http://logos.kodibg.org/cnn.png"},
  "Euronews":{"id":"Euronews", "group":"Новини","logo":""},
  "Bloomberg":{"id":"Bloomberg", "group":"Новини","logo":""},
  "Sky News":{"id":"Sky News", "group":"Новини","logo":""},
  "BBC Worldnews":{"id":"BBC World News", "group":"Новини","logo":""},
  "CNBC":{"id":"CNBC", "group":"Новини","logo":""},
  "France 24":{"id":"France 24", "group":"Новини","logo":""},
  "France 4 HD":{"id":"France 4 HD", "group":"Новини","logo":""},
  "TV5 Monde":{"id":"TV5 Monde", "group":"Новини","logo":""},
  "Al Jazeera Eng":{"id":"Al Jazeera English", "group":"Новини","logo":""},
  "France 2":{"id":"France 2", "group":"Новини","logo":""},
  "France 3 HD":{"id":"France 3 HD", "group":"Новини","logo":""},
  "Russia Today":{"id":"Russia Today", "group":"Новини","logo":""},
  "France 2 HD":{"id":"France 2 HD", "group":"Новини","logo":""},
  "CCTV 4":{"id":"CCTV 4", "group":"Новини","logo":""},
  "CCTV News":{"id":"CCTV News", "group":"Новини","logo":""},
  "RT News HD":{"id":"RT News HD", "group":"Документални","logo":""},
  "RT Docu HD":{"id":"RT Docu HD", "group":"Документални","logo":""},
  "CNN International HD":{"id":"CNN International HD", "group":"Новини","logo":""},
  "NHK World HD":{"id":"NHK World", "group":"Новини","logo":""},
  "NHK World":{"id":"NHK World", "group":"Новини","logo":""},
  "CCTV 9 Documentary":{"id":"CCTV 9 Documentary", "group":"Документални","logo":""},
  "BBC World HD":{"id":"BBC World News", "group":"Новини","logo":""},
  "FOX Life HD":{"id":"FOX Life HD", "group":"Филми","logo":""},
  "FOX Crime HD":{"id":"FOX Crime HD", "group":"Филми","logo":""},
  "ID Xtra HD":{"id":"ID Xtra HD", "group":"Документални","logo":""},
  "Discovery Turbo HD":{"id":"Discovery Turbo HD", "group":"Документални","logo":""},
  "Auto Motor Sport":{"id":"Auto Motor Sport", "group":"Спортни","logo":""},
  "Auto Motor Sport HD":{"id":"Auto Motor Sport HD", "group":"Спортни","logo":""},
  "AMS HD":{"id":"Auto Motor Sport HD", "group":"Спортни","logo":""},
  "Sky Sport HD 3":{"id":"Sky Sport HD 3", "group":"Спортни","logo":""},
  "Sky Sport HD 4":{"id":"Sky Sport HD 4", "group":"Спортни","logo":""},
  "Sky Sport HD 5":{"id":"Sky Sport HD 5", "group":"Спортни","logo":""},
  "Sky Sport HD 6":{"id":"Sky Sport HD 6", "group":"Спортни","logo":""},
  "Sky Bundesliga 1 HD":{"id":"Sky Bundesliga 1 HD", "group":"Спортни","logo":""},
  "Sport1 US HD":{"id":"Sport1 US HD", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sport1us.png"},
  "Sport1+ HD":{"id":"Sport1+ HD", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sport1.png"},
  "Eurosport DE HD":{"id":"Eurosport DE HD", "group":"Спортни","logo":""},
  "Diema Sport 2":{"id":"DiemaSport2", "group":"Спортни","logo":"http://logos.kodibg.org/diemasport2.png"},
  "Arena Sport 1 (SRB)":{"id":"Arena Sport 1 (SRB)", "group":"Спортни","logo":""},
  "Arena Sport 2 (SRB)":{"id":"Arena Sport 2 (SRB)", "group":"Спортни","logo":""},
  "Arena Sport 3 (SRB)":{"id":"Arena Sport 3 (SRB)", "group":"Спортни","logo":""},
  "Arena Sport 4 (SRB)":{"id":"Arena Sport 4 (SRB)", "group":"Спортни","logo":""},
  "Arena Sport 5 (SRB)":{"id":"Arena Sport 5 (SRB)", "group":"Спортни","logo":""},
  "Fight World HD":{"id":"fight_world_hd", "group":"Спортни","logo":""},
  "FightBox HD":{"id":"FightBox", "group":"Спортни","logo":"http://logos.kodibg.org/fightbox.png"},
  "Fast and Fun HD":{"id":"Fast and Fun HD", "group":"Спортни","logo":""},
  "Trace Sport Stars HD":{"id":"Trace Sport Stars HD", "group":"Спортни","logo":"http://logos.kodibg.org/tracesportstars.png"},
  "PO TV":{"id":"POTV", "group":"Регионални","logo":"http://logos.kodibg.org/potv.png"},
  "Черно море":{"id":"ChernoMore", "group":"Регионални","logo":"http://logos.kodibg.org/chernomore.png"},
  "VTV":{"id":"VTV", "group":"Национални","logo":"http://logos.kodibg.org/vtv.png"},
  "BG DNES":{"id":"BGDNES", "group":"Документални","logo":"http://logos.kodibg.org/bgdnestv.png"},
  "BG DNES HD":{"id":"BGDNES", "group":"Документални","logo":"http://logos.kodibg.org/bgdnestv.png"},
  "Bulgaria 24":{"id":"Bulgaria24", "group":"Национални","logo":"http://logos.kodibg.org/bulgaria24.png"},
  "Varna TV":{"id":"VarnaTV", "group":"Регионални","logo":"http://logos.kodibg.org/tvvarna.png"},
  "Канал 4":{"id":"kanal4", "group":"Регионални","logo":"http://logos.kodibg.org/kanal4.png"},
  "Bloomberg BG":{"id":"BloombergBG", "group":"Национални","logo":"http://logos.kodibg.org/bloombergtvbulgaria.png"},
  "Стойчев":{"id":"Stoichev", "group":"Регионални","logo":"http://logos.kodibg.org/tvstoichev.png"},
  "КИС 13":{"id":"kiss13", "group":"Регионални","logo":"http://logos.kodibg.org/kiss13.png"},
  "БНП ТВ":{"id":"БНП ТВ", "group":"Национални","logo":"http://logos.kodibg.org/bnptv.png"},
  "Agro TV":{"id":"AgroTV", "group":"Национални","logo":"http://logos.kodibg.org/agrotv.png"},
  "Alfa TV":{"id":"Alfa", "group":"Национални","logo":"http://logos.kodibg.org/alfa.png"},
  "Alfa":{"id":"Alfa", "group":"Национални","logo":"http://logos.kodibg.org/alfa.png"},
  "TV1":{"id":"TV1", "group":"Национални","logo":"http://logos.kodibg.org/tv1.png"},
  "TV1 HD":{"id":"TV1", "group":"Национални","logo":"http://logos.kodibg.org/tv1.png"},
  "TV 1 HD":{"id":"TV1", "group":"Национални","logo":"http://logos.kodibg.org/tv1.png"},
  "100% Auto Moto TV":{"id":"AutoMotorSport", "group":"Спортни","logo":"http://logos.kodibg.org/automoto.png"},
  "ВТК":{"id":"ВТК", "group":"Национални","logo":"http://logos.kodibg.org/vtk.png"},
  "Евроком":{"id":"Eurocom", "group":"Национални","logo":"http://logos.kodibg.org/evrokom.png"},
  "БХ ТВ":{"id":"БХ ТВ", "group":"Национални","logo":"http://logos.kodibg.org/bhtv.png"},
  "ПП ТВ":{"id":"ПП ТВ", "group":"Национални","logo":"http://logos.kodibg.org/pptv.png"},
  "Канал 0":{"id":"kanal0", "group":"Регионални","logo":"http://logos.kodibg.org/kanal0.png"},
  "Еврошанс":{"id":"Еврошанс", "group":"Спортни","logo":""},
  "Fishing & Hunting":{"id":"FishingHunting", "group":"Документални","logo":"http://logos.kodibg.org/thefishinghuntingchannel.png"},
  "BG Info":{"id":"BG Info", "group":"Документални","logo":"http://logos.kodibg.org/bginfo.png"},
  "HMTV HD":{"id":"HMTV HD", "group":"Документални","logo":"http://logos.kodibg.org/hmtv.png"},
  "M1":{"id":"M1", "group":"Музикални","logo":""},
  "M2":{"id":"M2", "group":"Музикални","logo":""},
  "Music Box (Укр)":{"id":"Music Box (Укр)", "group":"Музикални","logo":""},
  "Джус ТВ":{"id":"Джус ТВ", "group":"Музикални","logo":""},
  "Первый Инт. канал (тест)":{"id":"Первый Инт. канал (тест)", "group":"Руски","logo":""},
  "Vevo HD":{"id":"Vevo HD", "group":"Музикални","logo":""},
  "Djazz HD":{"id":"Djazz HD", "group":"Музикални","logo":""},
  "Brava HD":{"id":"Brava HD", "group":"Музикални","logo":""},
  "Classica HD":{"id":"Classica HD", "group":"Музикални","logo":"http://logos.kodibg.org/classica.png"},
  "Tiankov Music":{"id":"TiankovMusic", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},
  "Fen Folk":{"id":"FenFolk", "group":"Музикални","logo":"http://logos.kodibg.org/fenfolk.png"},
  "FEN HD":{"id":"FENTV", "group":"Музикални","logo":"http://logos.kodibg.org/fentv.png"},
  "Hit Mix Channel":{"id":"Hit Mix Channel", "group":"Музикални","logo":"http://logos.kodibg.org/hitmix.png"},
  "Фолклор HD":{"id":"FolklorTV", "group":"Музикални","logo":"http://logos.kodibg.org/folklortv.png"},
  "Balkanika HD":{"id":"Balkanika", "group":"Музикални","logo":"http://logos.kodibg.org/balkanika.png"},
  "BG Music HD":{"id":"BGMusicChannel", "group":"Музикални","logo":"http://logos.kodibg.org/bgmusicchannel.png"},
  "Roma TV":{"id":"roma_tv", "group":"Музикални","logo":""},
  "Roma TV HD":{"id":"roma_tv", "group":"Музикални","logo":""},
  "iConcerts HD":{"id":"iConcerts", "group":"Музикални","logo":"http://logos.kodibg.org/iconcerts.png"},
  "MTV Dance":{"id":"MTVDance", "group":"Музикални","logo":"http://logos.kodibg.org/mtvdance.png"},
  "MTV Live HD":{"id":"MTVLiveHD", "group":"Музикални","logo":"http://logos.kodibg.org/mtvlivehd.png"},
  "MTV":{"id":"MTV", "group":"Музикални","logo":"http://logos.kodibg.org/mtv.png"},
  "MTV Rocks":{"id":"MTVRocks", "group":"Музикални","logo":"http://logos.kodibg.org/mtvrocks.png"},
  "MTV Hits":{"id":"MTVhits", "group":"Музикални","logo":"http://logos.kodibg.org/mtvhits.png"},
  "VH1":{"id":"VH1", "group":"Музикални","logo":"http://logos.kodibg.org/vh1.png"},
  "VH1 Classic":{"id":"VH1 Classic", "group":"Музикални","logo":"http://logos.kodibg.org/vh1classic.png"},
  "Mezzo":{"id":"Mezzo", "group":"Музикални","logo":"http://logos.kodibg.org/mezzo.png"},
  "Mezzo Live HD":{"id":"Mezzolivehd", "group":"Музикални","logo":"http://logos.kodibg.org/mezzolivehd.png"},
  "Fashion TV":{"id":"Fashion TV", "group":"Тематични","logo":"http://logos.kodibg.org/fashiontv.png"},
  "Fashion HD":{"id":"Fashion HD", "group":"Тематични","logo":"http://logos.kodibg.org/fashiontv.png"},
  "Smash Hits":{"id":"Smash Hits", "group":"Музикални","logo":""},
  "F.O. HD":{"id":"F.O. HD", "group":"Тематични","logo":""},
  "Body and Balance":{"id":"Body and Balance", "group":"Тематични","logo":""},
  "World Fashion HD":{"id":"World Fashion HD", "group":"Тематични","logo":""},
  "F.O. TV":{"id":"F.O. TV", "group":"Тематични","logo":""},
  "Deluxe Lounge HD":{"id":"DeluxeLoungeHD", "group":"Тематични","logo":"http://logos.kodibg.org/deluxeloungehd.png"},
  "Luxe HD":{"id":"Luxe HD", "group":"Тематични","logo":""},
  "BG Music":{"id":"BGMusicChannel", "group":"Музикални","logo":"http://logos.kodibg.org/bgmusicchannel.png"},
  "The Voice":{"id":"TheVoice", "group":"Музикални","logo":"http://logos.kodibg.org/thevoicetv.png"},
  "City TV":{"id":"City", "group":"Музикални","logo":"http://logos.kodibg.org/citytv.png"},
  "359TV HD":{"id":"359TV", "group":"Музикални","logo":"http://logos.kodibg.org/359tv.png"},
  "Родина ТВ":{"id":"Родина ТВ", "group":"Музикални","logo":"http://logos.kodibg.org/rodinatv.png"},
  "BOX":{"id":"BoxTV", "group":"Музикални","logo":"http://logos.kodibg.org/boxtv.png"},
  "BOX HD":{"id":"BoxTV", "group":"Музикални","logo":"http://logos.kodibg.org/boxtv.png"},
  "BOX TV HD":{"id":"BoxTV", "group":"Музикални","logo":"http://logos.kodibg.org/boxtv.png"},
  "Kiss TV":{"id":"Kiss TV", "group":"Музикални","logo":""},
  "Juce TV":{"id":"Juce TV", "group":"Музикални","logo":""},
  "Deluxe Music":{"id":"DEDeluxeMusic", "group":"Музикални","logo":"http://logos.kodibg.org/deluxemusic.png"},
  "Deluxe Music HD":{"id":"DEDeluxeMusic", "group":"Музикални","logo":"http://logos.kodibg.org/deluxemusic.png"},
  "Magic TV":{"id":"MagicTV", "group":"Музикални","logo":"http://logos.kodibg.org/magictv.png"},
  "Планета":{"id":"Planeta", "group":"Музикални","logo":"http://logos.kodibg.org/planetatv.png"},
  "Планета HD":{"id":"PlanetaHD", "group":"Музикални","logo":"http://logos.kodibg.org/planetahd.png"},
  "Planeta":{"id":"Planeta", "group":"Музикални","logo":"http://logos.kodibg.org/planetahd.png"},
  "Planeta HD":{"id":"PlanetaHD", "group":"Музикални","logo":"http://logos.kodibg.org/planetahd.png"},
  "Планета Фолк":{"id":"PlanetaFolk", "group":"Музикални","logo":"http://logos.kodibg.org/planetafolk.png"},
  "FEN TV":{"id":"FENTV", "group":"Музикални","logo":"http://logos.kodibg.org/fentv.png"},
  "Fen TV HD":{"id":"FENTV", "group":"Музикални","logo":"http://logos.kodibg.org/fentv.png"},
  "Balkanika":{"id":"Balkanika", "group":"Музикални","logo":"http://logos.kodibg.org/balkanika.png"},
  "DSTV":{"id":"DSTV", "group":"Музикални","logo":"http://logos.kodibg.org/dstv.png"},
  "Фолклор ТВ":{"id":"FolklorTV", "group":"Музикални","logo":"http://logos.kodibg.org/folklortv.png"},
  "Тянков HD":{"id":"TiankovFolk", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},
  "Тянков Мюзик HD":{"id":"TiankovFolk", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},
  "Тянков ТВ":{"id":"TiankovFolk", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},
  "Salsa+":{"id":"Salsa+", "group":"Музикални","logo":""},
  "DM Sat":{"id":"DMSat", "group":"Музикални","logo":"http://logos.kodibg.org/dmsat.png"},
  "BN Music":{"id":"bn_music", "group":"Музикални","logo":""},
  "Shanson":{"id":"Shanson", "group":"Музикални","logo":""},
  "Музыка":{"id":"Музыка", "group":"Музикални","logo":""},
  "Music Box Russia":{"id":"Music Box Russia", "group":"Музикални","logo":""},
  "RCK":{"id":"RCK", "group":"Музикални","logo":""},
  "Jukebox":{"id":"Jukebox", "group":"Музикални","logo":""},
  "KCN Music 2":{"id":"KCN Music 2", "group":"Музикални","logo":""},
  "Super 7":{"id":"Super 7", "group":"Детски","logo":""},
  "Cartoon Network / TCM":{"id":"CartoonNetwork", "group":"Детски","logo":"http://logos.kodibg.org/cartoonnetwork.png"},
  "CN":{"id":"CartoonNetwork", "group":"Детски","logo":"http://logos.kodibg.org/cartoonnetwork.png"},
  "Boomerang":{"id":"Boomerang", "group":"Детски","logo":"http://logos.kodibg.org/boomerang.png"},
  "Fix and Foxi":{"id":"Fix and Foxi", "group":"Детски","logo":""},
  "eKids":{"id":"eKids", "group":"Детски","logo":"http://logos.kodibg.org/ekids.png"},
  "Nickelodeon":{"id":"Nickelodeon", "group":"Детски","logo":"http://logos.kodibg.org/nickelodeon.png"},
  "Nickelodeon HD":{"id":"nickelodeon_hd", "group":"Детски","logo":"http://logos.kodibg.org/nickelodeon.png"},
  "Nick Jr.":{"id":"NickJr", "group":"Детски","logo":"http://logos.kodibg.org/nickjr.png"},
  "KiKa HD":{"id":"KiKa HD", "group":"Детски","logo":""},
  "Baby TV":{"id":"BabyTV", "group":"Детски","logo":"http://logos.kodibg.org/babytv.png"},
  "Duck TV":{"id":"DuckTV", "group":"Детски","logo":"http://logos.kodibg.org/ducktv.png"},
  "Duck HD":{"id":"DuckTV", "group":"Детски","logo":"http://logos.kodibg.org/ducktv.png"},
  "Jim Jam":{"id":"JimJam", "group":"Детски","logo":"http://logos.kodibg.org/jimjam.png"},
  "Smile Of A Child":{"id":"Smile Of A Child", "group":"Детски","logo":""},
  "Disney Channel":{"id":"Disney", "group":"Детски","logo":"http://logos.kodibg.org/disney.png"},
  "Disney Jr.":{"id":"DisneyJunior", "group":"Детски","logo":"http://logos.kodibg.org/disneyjunior.png"},
  "Disney Cinemagic HD":{"id":"Disney Cinemagic HD", "group":"Детски","logo":""},
  "Disney TR":{"id":"Disney TR", "group":"Детски","logo":""},
  "Карусель":{"id":"karusel", "group":"Детски","logo":""},
  "Детский мир / Телеклуб":{"id":"Детский мир / Телеклуб", "group":"Детски","logo":""},
  "Тест: Disney RU":{"id":"Тест: Disney RU", "group":"Детски","logo":""},
  "RiC":{"id":"RiC", "group":"Детски","logo":""},
  "Veronica / Disney (NL)":{"id":"Veronica / Disney (NL)", "group":"Детски","logo":""},
  "Pink Kids":{"id":"Pink Kids", "group":"Детски","logo":""},
  "Cartoon TR":{"id":"Cartoon TR", "group":"Детски","logo":""},
  "TRT Cocuk":{"id":"TRT Cocuk", "group":"Детски","logo":""},
  "Planet Cocuk":{"id":"Planet Cocuk", "group":"Детски","logo":""},
  "ERT":{"id":"ERT", "group":"Детски","logo":""},
  "Armenia":{"id":"Armenia", "group":"Тематични","logo":""},
  "Armenia 1":{"id":"Armenia 1", "group":"Тематични","logo":""},
  "RT Spanish HD":{"id":"RT Spanish HD", "group":"Новини","logo":""},
  "Polonia":{"id":"Polonia", "group":"Тематични","logo":""},
  "TVR International":{"id":"TVR International", "group":"Тематични","logo":""},
  "RTP International":{"id":"RTP International", "group":"Тематични","logo":""},
  "RTVE":{"id":"RTVE", "group":"Тематични","logo":""},
  "TVE":{"id":"TVE", "group":"Тематични","logo":""},
  "Slovenija 2 TV":{"id":"Slovenija 2 TV", "group":"Тематични","logo":""},
  "RAI News":{"id":"RAI News", "group":"Италиански","logo":""},
  "RAI 1":{"id":"RAI 1", "group":"Италиански","logo":""},
  "RAI 2":{"id":"RAI 2", "group":"Италиански","logo":""},
  "RAI 3":{"id":"RAI 3", "group":"Италиански","logo":""},
  "RAI Scuola":{"id":"RAI Scuola", "group":"Италиански","logo":""},
  "RAI 1 HD":{"id":"RAI 1 HD", "group":"Италиански","logo":""},
  "RAI 2 HD":{"id":"RAI 2 HD", "group":"Италиански","logo":""},
  "RAI 3 HD":{"id":"RAI 3 HD", "group":"Италиански","logo":""},
  "RAI Sport 1 HD":{"id":"RAI Sport 1 HD", "group":"Спортни","logo":""},
  "ORF1":{"id":"ORF1", "group":"Немски","logo":""},
  "ORF2":{"id":"ORF2", "group":"Немски","logo":""},
  "Tagesschau 24":{"id":"Tagesschau 24", "group":"Немски","logo":""},
  "Tagesschau 24 HD":{"id":"Tagesschau 24 HD", "group":"Немски","logo":""},
  "Sat.1 Gold":{"id":"Sat.1 Gold", "group":"Немски","logo":""},
  "ORF1 HD":{"id":"ORF1 HD", "group":"Немски","logo":""},
  "ORF2 HD":{"id":"ORF2 HD", "group":"Немски","logo":""},
  "RTL HD":{"id":"RTL HD", "group":"Немски","logo":""},
  "RTL 2 HD":{"id":"RTL 2 HD", "group":"Немски","logo":""},
  "RTL":{"id":"RTL", "group":"Немски","logo":""},
  "RTL Nitro":{"id":"RTL Nitro", "group":"Немски","logo":""},
  "SAT1":{"id":"SAT1", "group":"Немски","logo":""},
  "PRO7":{"id":"PRO7", "group":"Немски","logo":""},
  "Kabel1":{"id":"Kabel1", "group":"Немски","logo":""},
  "VOX":{"id":"VOX", "group":"Немски","logo":""},
  "Super RTL ":{"id":"Super RTL ", "group":"Немски","logo":""},
  "3sat HD":{"id":"3sat HD", "group":"Немски","logo":""},
  "Anixe HD":{"id":"Anixe HD", "group":"Немски","logo":""},
  "N24":{"id":"N24", "group":"Немски","logo":""},
  "3sat":{"id":"3sat", "group":"Немски","logo":""},
  "WDR":{"id":"WDR", "group":"Немски","logo":""},
  "Arte HD":{"id":"Arte HD", "group":"Немски","logo":""},
  "ARD / Das Erste HD":{"id":"ARD / Das Erste HD", "group":"Немски","logo":""},
  "ZDF HD":{"id":"ZDF HD", "group":"Немски","logo":""},
  "Servus HD":{"id":"Servus HD", "group":"Немски","logo":""},
  "ZDF":{"id":"ZDF", "group":"Немски","logo":""},
  "N-TV":{"id":"N-TV", "group":"Немски","logo":""},
  "Eins Festival":{"id":"Eins Festival", "group":"Немски","logo":""},
  "RTL 2":{"id":"RTL 2", "group":"Немски","logo":""},
  "WDR HD":{"id":"WDR HD", "group":"Немски","logo":""},
  "Arte DE":{"id":"Arte DE", "group":"Немски","logo":""},
  "ZDF Info HD":{"id":"ZDF Info HD", "group":"Немски","logo":""},
  "ZDF Neo HD":{"id":"ZDF Neo HD", "group":"Немски","logo":""},
  "ZDF Kultur HD":{"id":"ZDF Kultur HD", "group":"Немски","logo":""},
  "Phoenix":{"id":"Phoenix", "group":"Немски","logo":""},
  "Discovery DE HD":{"id":"Discovery DE HD", "group":"Немски","logo":""},
  "Nat Geo HD DE":{"id":"Nat Geo HD DE", "group":"Немски","logo":""},
  "Natgeo Wild EU HD":{"id":"Natgeo Wild EU HD", "group":"Немски","logo":""},
  "N-TV HD":{"id":"N-TV HD", "group":"Немски","logo":""},
  "Sky Hits HD":{"id":"Sky Hits HD", "group":"Филми","logo":""},
  "Sky Action HD":{"id":"Sky Action HD", "group":"Филми","logo":""},
  "Sky Atlantic HD":{"id":"Sky Atlantic HD", "group":"Филми","logo":""},
  "Sky Cinema HD":{"id":"Sky Cinema HD", "group":"Филми","logo":""},
  "13th Street HD":{"id":"13th Street HD", "group":"Филми","logo":""},
  "TNT Film":{"id":"TNT Film", "group":"Филми","logo":""},
  "TNT Serie HD":{"id":"TNT Serie HD", "group":"Филми","logo":""},
  "SyFy HD":{"id":"SyFy HD", "group":"Филми","logo":""},
  "MGM HD":{"id":"MGM HD", "group":"Филми","logo":""},
  "Eins Festival HD ":{"id":"Eins Festival HD ", "group":"Филми","logo":""},
  "Eins Plus HD ":{"id":"Eins Plus HD ", "group":"Филми","logo":""},
  "SR Fernsehen HD":{"id":"SR Fernsehen HD", "group":"Немски","logo":""},
  "Матч! Футбол 1 HD":{"id":"Матч! Футбол 1 HD", "group":"Спортни","logo":"http://logos.kodibg.org/matchtv.png"},
  "Матч! Футбол 2 HD":{"id":"Матч! Футбол 2 HD", "group":"Спортни","logo":"http://logos.kodibg.org/matchtv.png"},
  "Матч! Футбол 3 HD":{"id":"Матч! Футбол 3 HD", "group":"Спортни","logo":"http://logos.kodibg.org/matchtv.png"},
  "Наш Футбол HD":{"id":"Наш Футбол HD", "group":"Спортни","logo":""},
  "Матч! ТВ HD":{"id":"Матч! ТВ HD", "group":"Спортни","logo":"http://logos.kodibg.org/matchtv.png"},
  "Конный Мир HD":{"id":"Конный Мир HD", "group":"Спортни","logo":""},
  "Viasat Sport HD":{"id":"Viasat Sport HD", "group":"Спортни","logo":""},
  "Тест: Первый канал  (RU)":{"id":"Тест: Первый канал  (RU)", "group":"Руски","logo":""},
  "Тест: Наш Футбол":{"id":"Тест: Наш Футбол", "group":"Спорт","logo":""},
  "Русский Экстрим":{"id":"Русский Экстрим", "group":"Спортни","logo":""},
  "Мир ТВ":{"id":"Мир ТВ", "group":"Руски","logo":""},
  "ТБН Россия":{"id":"ТБН Россия", "group":"Руски","logo":""},
  "Наука 2.0":{"id":"Наука 2.0", "group":"Руски","logo":""},
  "Россия 1":{"id":"Россия 1", "group":"Руски","logo":""},
  "Russian Travel Guide":{"id":"Russian Travel Guide", "group":"Руски","logo":""},
  "Матч ТВ":{"id":"Матч ТВ", "group":"Спортни","logo":"http://logos.kodibg.org/matchtv.png"},
  "Ю":{"id":"Ю", "group":"Руски","logo":""},
  "Телеканал 2x2":{"id":"Телеканал 2x2", "group":"Руски","logo":""},
  "Наука":{"id":"Наука", "group":"Руски","logo":""},
  "Еврокино":{"id":"Еврокино", "group":"Руски","logo":""},
  "Моя Планета":{"id":"Моя Планета", "group":"Руски","logo":""},
  "НТВ":{"id":"НТВ", "group":"Руски","logo":""},
  "РЕН ТВ":{"id":"РЕН ТВ", "group":"Руски","logo":""},
  "FOX RU HD":{"id":"FOX RU HD", "group":"Руски","logo":""},
  "TV1000 Комеди HD":{"id":"TV1000 Комеди HD", "group":"Руски","logo":""},
  "TV1000 Мегахит HD":{"id":"TV1000 Мегахит HD", "group":"Руски","logo":""},
  "TV1000 Премиум HD":{"id":"TV1000 Премиум HD", "group":"Руски","logo":""},
  "Тест: Русский Иллюзион":{"id":"Тест: Русский Иллюзион", "group":"Руски","logo":""},
  "Илюзион+":{"id":"Илюзион+", "group":"Руски","logo":""},
  "СТС Россия":{"id":"СТС Россия", "group":"Руски","logo":""},
  "TF1 HD":{"id":"TF1 HD", "group":"Френски","logo":""},
  "La Une HD":{"id":"La Une HD", "group":"Френски","logo":""},
  "La Deux":{"id":"La Deux", "group":"Френски","logo":""},
  "La Trois":{"id":"La Trois", "group":"Френски","logo":""},
  "Club RTL":{"id":"Club RTL", "group":"Френски","logo":""},
  "Plug RTL":{"id":"Plug RTL", "group":"Френски","logo":""},
  "RTL TVi HD":{"id":"RTL TVi HD", "group":"Френски","logo":""},
  "Animaux":{"id":"Animaux", "group":"Френски","logo":""},
  "NT1":{"id":"NT1", "group":"Френски","logo":""},
  "France 24 FR":{"id":"France 24 FR", "group":"Френски","logo":""},
  "BFM HD":{"id":"BFM HD", "group":"Френски","logo":""},
  "CCTV French":{"id":"CCTV French", "group":"Френски","logo":""},
  "AB3":{"id":"AB3", "group":"Френски","logo":""},
  "Toute L'histoire":{"id":"Toute L'histoire", "group":"Френски","logo":""},
  "RTL 9 HD":{"id":"RTL 9 HD", "group":"Френски","logo":""},
  "BFM Business HD":{"id":"BFM Business HD", "group":"Френски","logo":""},
  "TV 5 Monde HD ":{"id":"TV 5 Monde HD ", "group":"Френски","logo":""},
  "Интер (Укр)":{"id":"Интер (Укр)", "group":"Руски","logo":""},
  "1+1 (Укр)":{"id":"1+1 (Укр)", "group":"Руски","logo":""},
  "2+2 (Укр)":{"id":"2+2 (Укр)", "group":"Руски","logo":""},
  "ICTV (Укр)":{"id":"ICTV (Укр)", "group":"Руски","logo":""},
  "СТБ (Укр)":{"id":"СТБ (Укр)", "group":"Руски","logo":""},
  "НТН (Укр)":{"id":"НТН (Укр)", "group":"Руски","logo":""},
  "ТЕТ (Укр)":{"id":"ТЕТ (Укр)", "group":"Руски","logo":""},
  "Новый (Укр)":{"id":"Новый (Укр)", "group":"Руски","logo":""},
  "112 HD (Укр)":{"id":"112 HD (Укр)", "group":"Руски","logo":""},
  "Телеканал новостей 24 (Укр)":{"id":"Телеканал новостей 24 (Укр)", "group":"Руски","logo":""},
  "5 канал (Укр)":{"id":"5 канал (Укр)", "group":"Руски","logo":""},
  "Тонис HD (Укр)":{"id":"Тонис HD (Укр)", "group":"Руски","logo":""},
  "HD Fashion (Укр)":{"id":"HD Fashion (Укр)", "group":"Руски","logo":""},
  "Kanal 7 (tr)":{"id":"Kanal 7 (tr)", "group":"Турски","logo":""},
  "TRT 1":{"id":"TRT 1", "group":"Турски","logo":""},
  "Salon 1 HD":{"id":"Salon 1 HD", "group":"Турски","logo":""},
  "Salon 2 HD":{"id":"Salon 2 HD", "group":"Турски","logo":""},
  "Salon 3 HD":{"id":"Salon 3 HD", "group":"Турски","logo":""},
  "Kanal D":{"id":"Kanal D", "group":"Турски","logo":""},
  "Moviemax Premier 1 HD":{"id":"Moviemax Premier 1 HD", "group":"Турски","logo":""},
  "Rumeli TV":{"id":"Rumeli TV", "group":"Турски","logo":""},
  "Yaban TV":{"id":"Yaban TV", "group":"Турски","logo":""},
  "Flash TV":{"id":"Flash TV", "group":"Турски","logo":""},
  "TRT":{"id":"TRT", "group":"Турски","logo":""},
  "NTV Spor":{"id":"NTV Spor", "group":"Турски","logo":""},
  "TRT Spor":{"id":"TRT Spor", "group":"Турски","logo":""},
  "TRT Avaz":{"id":"TRT Avaz", "group":"Турски","logo":""},
  "TRT Arapca":{"id":"TRT Arapca", "group":"Турски","logo":""},
  "TRT Music":{"id":"TRT Music", "group":"Турски","logo":""},
  "Euro D":{"id":"Euro D", "group":"Турски","logo":""},
  "TRT Haber":{"id":"TRT Haber", "group":"Турски","logo":""},
  "NTV TR":{"id":"NTV TR", "group":"Турски","logo":""},
  "A Spor":{"id":"A Spor", "group":"Турски","logo":""},
  "A Spor HD":{"id":"A Spor HD", "group":"Турски","logo":""},
  "Star TV":{"id":"Star TV", "group":"Турски","logo":""},
  "Kanal 3":{"id":"Kanal 3", "group":"Турски","logo":""},
  "Euro Star":{"id":"Euro Star", "group":"Турски","logo":""},
  "Kardelen":{"id":"Kardelen", "group":"Турски","logo":""},
  "Abant TV":{"id":"Abant TV", "group":"Турски","logo":""},
  "GTV Guneydogu TV":{"id":"GTV Guneydogu TV", "group":"Турски","logo":""},
  "Kanal 26 TR":{"id":"Kanal 26 TR", "group":"Турски","logo":""},
  "TV 8":{"id":"TV 8", "group":"Турски","logo":""},
  "Show TV":{"id":"Show TV", "group":"Турски","logo":""},
  "FOX TR":{"id":"FOX TR", "group":"Турски","logo":""},
  "ATV Avrupa":{"id":"ATV Avrupa", "group":"Турски","logo":""},
  "Haber Turk":{"id":"Haber Turk", "group":"Турски","logo":""},
  "Planet Turk":{"id":"Planet Turk", "group":"Турски","logo":""},
  "Kanal 5":{"id":"Kanal 5", "group":"Турски","logo":""},
  "A Haber":{"id":"A Haber", "group":"Турски","logo":""},
  "ATV HD":{"id":"ATV HD", "group":"Турски","logo":""},
  "Semerkand  HD":{"id":"Semerkand  HD", "group":"Турски","logo":""},
  "Star TV HD":{"id":"Star TV HD", "group":"Турски","logo":""},
  "Beyaz TV HD":{"id":"Beyaz TV HD", "group":"Турски","logo":""},
  "CNN Turk":{"id":"CNN Turk", "group":"Турски","logo":""},
  "NTV Avrupa":{"id":"NTV Avrupa", "group":"Турски","logo":""},
  "Kanal t":{"id":"Kanal t", "group":"Турски","logo":""},
  "NR1 Turk HD":{"id":"NR1 Turk HD", "group":"Турски","logo":""},
  "Kral Pop":{"id":"Kral Pop", "group":"Турски","logo":""},
  "Kral TV":{"id":"Kral TV", "group":"Турски","logo":""},
  "Dream Turk":{"id":"Dream Turk", "group":"Турски","logo":""},
  "Dream TV":{"id":"Dream TV", "group":"Турски","logo":""},
  "Viva TR":{"id":"Viva TR", "group":"Турски","logo":""},
  "Planet Mutfak":{"id":"Planet Mutfak", "group":"Турски","logo":""},
  "Planet Pembe":{"id":"Planet Pembe", "group":"Турски","logo":""},
  "PPV Info":{"id":"PPV Info", "group":"Турски","logo":""},
  "PPV 1 (demo)":{"id":"PPV 1 (demo)", "group":"","logo":""},
  "PPV 2 (demo)":{"id":"PPV 2 (demo)", "group":"","logo":""},
  "PPV 3 (demo)":{"id":"PPV 3 (demo)", "group":"","logo":""},
  "PPV 4 (demo)":{"id":"PPV 4 (demo)", "group":"","logo":""},
  "PPV 5 (demo)":{"id":"PPV 5 (demo)", "group":"","logo":""},
  "PPV 6 (demo)":{"id":"PPV 6 (demo)", "group":"","logo":""},
  "Film+":{"id":"Film+", "group":"Филми","logo":"http://logos.kodibg.org/filmplus.png"},
  "Film+ HD":{"id":"Film+", "group":"Филми","logo":"http://logos.kodibg.org/filmplus.png"},
  "FilmBox Extra HD":{"id":"FilmBoXtraHD", "group":"Филми","logo":"http://logos.kodibg.org/filmboxextra.png"},
  "FilmBox Plus HD":{"id":"FilmBoxPlusHD", "group":"Филми","logo":"http://logos.kodibg.org/filmboxplus.png"},
  "FilmBox Arthouse":{"id":"FilmboxArthouseHD", "group":"Филми","logo":"http://logos.kodibg.org/filmboxarthouse.png"},
  "Action+ HD":{"id":"ActionPlus", "group":"Филми","logo":"http://logos.kodibg.org/actionplus.png"},
  "Cinema+":{"id":"CinemaPlus", "group":"Филми","logo":"http://logos.kodibg.org/cinemaplus.png"},
  "Comedy+":{"id":"ComedyPlus", "group":"Филми","logo":"http://logos.kodibg.org/comedyplus.png"},
  "Sky 1":{"id":"Sky 1", "group":"Немски","logo":""},
  "Sky 2":{"id":"Sky 2", "group":"Немски","logo":""},
  "Sky 3D de":{"id":"Sky 3D de", "group":"Немски","logo":""},
  "and TV HD":{"id":"and TV HD", "group":"Немски","logo":""},
  "RTL Z HD (NL)":{"id":"RTL Z HD (NL)", "group":"Немски","logo":""},
  "NPO 1 (NL)":{"id":"NPO 1 (NL)", "group":"Немски","logo":""},
  "NPO 2 (NL)":{"id":"NPO 2 (NL)", "group":"Немски","logo":""},
  "NPO 3 (NL)":{"id":"NPO 3 (NL)", "group":"Немски","logo":""},
  "RTL 4 NL":{"id":"RTL 4 NL", "group":"Немски","logo":""},
  "RTL 5 NL":{"id":"RTL 5 NL", "group":"Немски","logo":""},
  "RTL 7 HD (NL)":{"id":"RTL 7 HD (NL)", "group":"Немски","logo":""},
  "Film1 Action NL":{"id":"Film1 Action NL", "group":"Немски","logo":""},
  "Film1 Comedy Kids NL":{"id":"Film1 Comedy Kids NL", "group":"Немски","logo":""},
  "Film1 Premiere NL":{"id":"Film1 Premiere NL", "group":"Немски","logo":""},
  "SBS 6 (NL)":{"id":"SBS 6 (NL)", "group":"Немски","logo":""},
  "Setanta":{"id":"Setanta", "group":"Спортни","logo":""},
  "Motors TV HD":{"id":"Motors TV HD", "group":"Спортни","logo":""},
  "Motors UK":{"id":"Motors UK", "group":"Спортни","logo":""},
  "Premier Sports":{"id":"Premier Sports", "group":"Спортни","logo":""},
  "Racing UK":{"id":"Racing UK", "group":"Спортни","logo":""},
  "Fuel TV HD":{"id":"Fuel TV", "group":"Спортни","logo":""},
  "Box Nation":{"id":"Box Nation", "group":"Спортни","logo":""},
  "beIN Sports 1 HD (fr)":{"id":"beIN Sports 1 HD (fr)", "group":"Спортни","logo":""},
  "beIN Sports 2 HD (fr)":{"id":"beIN Sports 2 HD (fr)", "group":"Спортни","logo":""},
  "beIN Sports 3 HD (fr)":{"id":"beIN Sports 3 HD (fr)", "group":"Спортни","logo":""},
  "FOX Sports 1 NL":{"id":"FOX Sports 1 NL", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports1.png"},
  "FOX Sports 2 NL":{"id":"FOX Sports 2 NL", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports2.png"},
  "FOX Sports 3 NL":{"id":"FOX Sports 3 NL", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports3.png"},
  "FOX Sports 4 NL":{"id":"FOX Sports 4 NL", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports4.png"},
  "FOX Sports 5 NL":{"id":"FOX Sports 5 NL", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports5.png"},
  "FOX Sports 6 NL":{"id":"FOX Sports 6 NL", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports6.png"},
  "Sky Action":{"id":"Sky Action", "group":"Филми","logo":""},
  "Sky Comedy":{"id":"Sky Comedy", "group":"Филми","logo":""},
  "Sky SciFi/Horror":{"id":"Sky SciFi/Horror", "group":"Филми","logo":""},
  "Sky Select":{"id":"Sky Select", "group":"Филми","logo":""},
  "Sky Family":{"id":"Sky Family", "group":"Филми","logo":""},
  "Sky Premiere +1":{"id":"Sky Premiere +1", "group":"Филми","logo":""},
  "Sky Drama":{"id":"Sky Drama", "group":"Филми","logo":""},
  "Movies 4 Men":{"id":"Movies 4 Men", "group":"Филми","logo":""},
  "Comedy Central UK":{"id":"Comedy Central UK", "group":"Филми","logo":""},
  "Sony Movie Channel":{"id":"Sony Movie Channel", "group":"Филми","logo":""},
  "БНТ1 LQ":{"id":"БНТ1", "group":"Национални","logo":""},
  "bTV LQ":{"id":"bTV", "group":"Национални","logo":""},
  "Nova LQ":{"id":"Nova", "group":"Национални","logo":""},
  "bTV Comedy LQ":{"id":"bTVComedy", "group":"Филми","logo":""},
  "bTV Cinema LQ":{"id":"bTVCinema", "group":"Филми","logo":""},
  "bTV Action LQ":{"id":"bTVAction", "group":"Филми","logo":""},
  "KinoNova LQ":{"id":"KinoNova", "group":"Филми","logo":""},
  "Diema LQ":{"id":"Diema", "group":"Филми","logo":""},
  "FOX Life LQ":{"id":"FOXLife", "group":"Филми","logo":""},
  "FOX Crime LQ":{"id":"FOXCrime", "group":"Филми","logo":""},
  "FOX LQ":{"id":"FOX", "group":"Филми","logo":""},
  "БНТ2 LQ":{"id":"BNT2", "group":"Национални","logo":""},
  "ТВ Европа LQ":{"id":"tveurope", "group":"Национални","logo":""},
  "NOVAsport LQ":{"id":"NOVAsport", "group":"Спортни","logo":""},
  "RING LQ":{"id":"RING", "group":"Спортни","logo":""},
  "Eurosport LQ":{"id":"Eurosport", "group":"Спортни","logo":""},
  "Eurosport 2 LQ":{"id":"Eurosport2", "group":"Спортни","logo":""},
  "Sport+ LQ":{"id":"SportPlusHD", "group":"Спортни","logo":""},
  "F+ LQ":{"id":"FPlus", "group":"Спортни","logo":""},
  "TV+ LQ":{"id":"TVPlus", "group":"Национални","logo":""},
  "Discovery LQ":{"id":"Discovery", "group":"Документални","logo":""},
  "Animal Planet LQ":{"id":"AnimalPlanet", "group":"Документални","logo":""},
  "Diema Family LQ":{"id":"DiemaFamily", "group":"Филми","logo":""},
  "BTV Lady LQ":{"id":"BTVLady", "group":"Филми","logo":""},
  "24 Kitchen LQ":{"id":"24Kitchen", "group":"Тематични","logo":""},
  "Diema Sport LQ":{"id":"DiemaSport", "group":"Спортни","logo":""},
  "Diema Sport 2 LQ":{"id":"DiemaSport2", "group":"Спортни","logo":""},
  "Cartoon Net LQ":{"id":"CartoonNet", "group":"Детски","logo":""},
  "Disney LQ":{"id":"Disney", "group":"Детски","logo":""},
  "NatGeo LQ":{"id":"NatGeo", "group":"Документални","logo":""},
  "TLC LQ":{"id":"TLC", "group":"Тематични","logo":""},
  "Hobby LQ":{"id":"Hobby", "group":"Документални","logo":""},
  "Travel LQ":{"id":"TravelHD", "group":"Документални","logo":""},
  "Hstory LQ":{"id":"Hstory", "group":"Документални","logo":""},
  "Diva LQ":{"id":"Diva", "group":"Тематични","logo":""},
  "City LQ":{"id":"City", "group":"Музикални","logo":""},
  "Planeta LQ":{"id":"Planeta", "group":"Музикални","logo":""},
  "Planeta Folk LQ":{"id":"PlanetaFolk", "group":"Музикални","logo":""},
  "DM SAT LQ":{"id":"DMSAT", "group":"Музикални","logo":""},
  "BG Music LQ":{"id":"BGMusic", "group":"Музикални","logo":""},
  "Balkanika LQ":{"id":"Balkanika", "group":"Музикални","logo":""},
  "Фолклор LQ":{"id":"Фолклор", "group":"Музикални","logo":""},
  "Arirang":{"id":"Arirang", "group":"Музикални","logo":""},
  "LIG TV":{"id":"LIG TV", "group":"Спортни","logo":""},
  "LIG TV 2":{"id":"LIG TV 2", "group":"Спортни","logo":""},
  "LIG TV 3":{"id":"LIG TV 3", "group":"Спортни","logo":""},
  "Digi Sport 1":{"id":"Digi Sport 1", "group":"Спортни","logo":""},
  "Digi Sport 2":{"id":"Digi Sport 2", "group":"Спортни","logo":""},
  "Sport Klub 1 HR":{"id":"Sport Klub 1 HR", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub1.png"},
  "Sport Klub 2 HR":{"id":"Sport Klub 2 HR", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub2.png"},
  "Sport Klub 3 HR":{"id":"Sport Klub 3 HR", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub3.png"},
  "Sport Klub 1":{"id":"Sport Klub 1", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub1.png"},
  "Sport Klub 2":{"id":"Sport Klub 2", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub2.png"},
  "Sport Klub 3 HD":{"id":"Sport Klub 3 HD", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub3.png"},
  "Sport Klub 4":{"id":"Sport Klub 4", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub4.png"},
  "Sport Klub 5":{"id":"Sport Klub 5", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub5.png"},
  "Sport Klub 6":{"id":"Sport Klub 6", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub6.png"},
  "Nova Sport 2 HD (CZ)":{"id":"Nova Sport 2 HD (CZ)", "group":"Спортни","logo":""},
  "Eurosport 360 HD 1":{"id":"Eurosport 360 HD 1", "group":"Спортни","logo":""},
  "Eurosport 360 HD 2":{"id":"Eurosport 360 HD 2", "group":"Спортни","logo":""},
  "beIN Sports 1 (ar)":{"id":"beIN Sports 1 (ar)", "group":"Спортни","logo":""},
  "beIN Sports 2 (ar)":{"id":"beIN Sports 2 (ar)", "group":"Спортни","logo":""},
  "beIN Sports 4 (ar)":{"id":"beIN Sports 4 (ar)", "group":"Спортни","logo":""},
  "Arena Sport 1 HD (HR)":{"id":"Arena Sport 1 HD (HR)", "group":"Спортни","logo":""},
  "Arena Sport 2 HD (HR)":{"id":"Arena Sport 2 HD (HR)", "group":"Спортни","logo":""},
  "Arena Sport 3 HD (HR)":{"id":"Arena Sport 3 HD (HR)", "group":"Спортни","logo":""},
  "Arena Sport 4 HD (HR)":{"id":"Arena Sport 4 HD (HR)", "group":"Спортни","logo":""},
  "Arena Sport 5 HD (HR)":{"id":"Arena Sport 5 HD (HR)", "group":"Спортни","logo":""},
  "Bein Sports HD (es)":{"id":"Bein Sports HD (es)", "group":"Спортни","logo":""},
  "Canal+ Golf HD":{"id":"Canal+ Golf HD", "group":"Спортни","logo":""},
  "Canal+ Deportes HD":{"id":"Canal+ Deportes HD", "group":"Спортни","logo":""},
  "Canal+ Toros HD":{"id":"Canal+ Toros HD", "group":"Спортни","logo":""},
  "Movistar F1 HD":{"id":"Movistar F1 HD", "group":"Филми","logo":""},
  "Movistar GP HD":{"id":"Movistar GP HD", "group":"Филми","logo":""},
  "Private":{"id":"Private", "group":"Възрастни","logo":""},
  "Sexto Senso":{"id":"Sexto Senso", "group":"Възрастни","logo":""},
  "SCT Exotica":{"id":"SCT Exotica", "group":"Възрастни","logo":""},
  "TGirls":{"id":"TGirls", "group":"Възрастни","logo":""},
  "SCT Satisfaction":{"id":"SCT Satisfaction", "group":"Възрастни","logo":""},
  "Penthouse HD1":{"id":"Penthouse HD1", "group":"Възрастни","logo":""},
  "Hustler HD":{"id":"Hustler HD", "group":"Възрастни","logo":""},
  "Redlight HD":{"id":"Redlight HD", "group":"Възрастни","logo":""},
  "Dorcel HD":{"id":"Dorcel HD", "group":"Възрастни","logo":""},
  "EroX":{"id":"EroX", "group":"Възрастни","logo":""},
  "EroXX HD":{"id":"EroXX HD", "group":"Възрастни","logo":""},
  "Hustler TV":{"id":"Hustler TV", "group":"Възрастни","logo":""},
  "Brazzers TV":{"id":"Brazzers TV", "group":"Възрастни","logo":""},
  "Dusk!":{"id":"Dusk!", "group":"Възрастни","logo":""},
  "SuperOne":{"id":"SuperOne", "group":"Възрастни","logo":""},
  "Dorcel TV":{"id":"Dorcel TV", "group":"Възрастни","logo":""},
  "French Lover":{"id":"French Lover", "group":"Възрастни","logo":""},
  "Passion XXX":{"id":"Passion XXX", "group":"Възрастни","logo":""},
  "CentoCento":{"id":"CentoCento", "group":"Възрастни","logo":""},
  "SCT Teleitalia":{"id":"SCT Teleitalia", "group":"Възрастни","logo":""},
  "SCT Boy & Boy":{"id":"SCT Boy & Boy", "group":"Възрастни","logo":""},
  "XXL HD":{"id":"XXL HD", "group":"Възрастни","logo":""},
  "Pink Plus":{"id":"Pink Plus", "group":"Сръбски","logo":""},
  "Pink 2":{"id":"Pink 2", "group":"Сръбски","logo":""},
  "Pink 3":{"id":"Pink 3", "group":"Сръбски","logo":""},
  "Pink M":{"id":"Pink M", "group":"Сръбски","logo":""},
  "Pink Reality":{"id":"Pink Reality", "group":"Сръбски","logo":""},
  "Pink Film":{"id":"Pink Film", "group":"Сръбски","logo":""},
  "Pink Movies":{"id":"Pink Movies", "group":"Сръбски","logo":""},
  "Pink Premium":{"id":"Pink Premium", "group":"Сръбски","logo":""},
  "Pink Comedy":{"id":"Pink Comedy", "group":"Сръбски","logo":""},
  "Pink Thriller":{"id":"Pink Thriller", "group":"Сръбски","logo":""},
  "Pink Horror":{"id":"Pink Horror", "group":"Сръбски","logo":""},
  "Pink Rommance":{"id":"Pink Rommance", "group":"Сръбски","logo":""},
  "Pink Crime":{"id":"Pink Crime", "group":"Сръбски","logo":""},
  "Pink Action":{"id":"Pink Action", "group":"Сръбски","logo":""},
  "Pink World":{"id":"Pink World", "group":"Сръбски","logo":""},
  "Pink Western":{"id":"Pink Western", "group":"Сръбски","logo":""},
  "Pink Sci-Fi":{"id":"Pink Sci-Fi", "group":"Сръбски","logo":""},
  "Pink Soap":{"id":"Pink Soap", "group":"Сръбски","logo":""},
  "Pink Pedia":{"id":"Pink Pedia", "group":"Сръбски","logo":""},
  "Pink Kuvar":{"id":"Pink Kuvar", "group":"Сръбски","logo":""},
  "Pink Serie":{"id":"Pink Serie", "group":"Сръбски","logo":""},
  "Pink Extra":{"id":"Pink Extra", "group":"Сръбски","logo":""},
  "Pink Zabava":{"id":"Pink Zabava", "group":"Сръбски","logo":""},
  "Pink Folk":{"id":"Pink Folk", "group":"Сръбски","logo":""},
  "Pink Folk 2":{"id":"Pink Folk 2", "group":"Сръбски","logo":""},
  "Pink Music":{"id":"Pink Music", "group":"Сръбски","logo":""},
  "Pink Hits 2":{"id":"Pink Hits 2", "group":"Сръбски","logo":""},
  "Pink-N-Roll":{"id":"Pink-N-Roll", "group":"Сръбски","logo":""},
  "Pink":{"id":"Pink", "group":"Сръбски","logo":""},
  "Happy RS":{"id":"Happy RS", "group":"Сръбски","logo":""},
  "Prva RS":{"id":"Prva RS", "group":"Сръбски","logo":""},
  "РТС 1":{"id":"РТС 1", "group":"Сръбски","logo":""},
  "РТС 2":{"id":"РТС 2", "group":"Сръбски","logo":""},
  "РТС 3":{"id":"РТС 3", "group":"Сръбски","logo":""},
  "B92":{"id":"B92", "group":"Сръбски","logo":""},
  "Grand":{"id":"Grand", "group":"Сръбски","logo":""},
  "Grand 2":{"id":"Grand 2", "group":"Сръбски","logo":""},
  "Hayat Folk":{"id":"Hayat Folk", "group":"Сръбски","logo":""},
  "Hayat Music":{"id":"Hayat Music", "group":"Сръбски","logo":""},
  "Сител MK":{"id":"Сител MK", "group":"Сръбски","logo":""},
  "MRTV 1":{"id":"MRTV 1", "group":"Сръбски","logo":""},
  "MRTV 2":{"id":"MRTV 2", "group":"Сръбски","logo":""},
  "MRTV 3":{"id":"MRTV 3", "group":"Сръбски","logo":""},
  "Телма MK":{"id":"Телма MK", "group":"Сръбски","logo":""},
  "Алфа MK":{"id":"Алфа MK", "group":"Сръбски","logo":""},
  "Канал 5 MK":{"id":"Канал 5 MK", "group":"Сръбски","logo":""},
  "24 Вести MK":{"id":"24 Вести MK", "group":"Сръбски","logo":""},
  "Nova TV MK":{"id":"Nova TV MK", "group":"Сръбски","logo":""},
  "Premier Sports HD":{"id":"Premier Sports HD", "group":"Спортни","logo":""},
  "Racing UK HD":{"id":"Racing UK HD", "group":"Спортни","logo":""},
  "BNT1 +1":{"id":"BNT1 +1", "group":"Национални","logo":""},
  "BTV +1":{"id":"BTV +1", "group":"Национални","logo":""},
  "Nova +1":{"id":"Nova +1", "group":"Национални","logo":""},
  "BNT1 +2":{"id":"BNT1 +2", "group":"Национални","logo":""},
  "BTV +2":{"id":"BTV +2", "group":"Национални","logo":""},
  "Nova +2":{"id":"Nova +2", "group":"Национални","logo":""},
  "BNT1 +7":{"id":"BNT1 +7", "group":"Национални","logo":""},
  "BTV +7":{"id":"BTV +7", "group":"Национални","logo":""},
  "Nova +7":{"id":"Nova +7", "group":"Национални","logo":""},
  "BNT1 +24":{"id":"BNT1 +24", "group":"Национални","logo":""},
  "BTV +24":{"id":"BTV +24", "group":"Национални","logo":""},
  "Nova +24":{"id":"Nova +24", "group":"Национални","logo":""},
  "BNT1 +48":{"id":"BNT1 +48", "group":"Национални","logo":""},
  "BTV +48":{"id":"BTV +48", "group":"Национални","logo":""},
  "Nova +48":{"id":"Nova +48", "group":"Национални","logo":""},
  "BNT1 +1 LQ":{"id":"BNT1 +1 LQ", "group":"Национални","logo":""},
  "BTV +1 LQ":{"id":"BTV +1 LQ", "group":"Национални","logo":""},
  "Nova +1 LQ ":{"id":"Nova +1 LQ ", "group":"Национални","logo":""},
  "BNT1 +2 LQ":{"id":"BNT1 +2 LQ", "group":"Национални","logo":""},
  "BTV +2 LQ":{"id":"BTV +2 LQ", "group":"Национални","logo":""},
  "Nova +2 LQ":{"id":"Nova +2 LQ", "group":"Национални","logo":""},
  "BNT1 +7 LQ":{"id":"BNT1 +7 LQ", "group":"Национални","logo":""},
  "BTV +7 LQ":{"id":"BTV +7 LQ", "group":"Национални","logo":""},
  "Nova +7 LQ":{"id":"Nova +7 LQ", "group":"Национални","logo":""},
  "BNT1 +24 LQ":{"id":"BNT1 +24 LQ", "group":"Национални","logo":""},
  "BTV +24 LQ":{"id":"BTV +24 LQ", "group":"Национални","logo":""},
  "Nova +24 LQ":{"id":"Nova +24 LQ", "group":"Национални","logo":""},
  "BNT1 +48 LQ":{"id":"BNT1 +48 LQ", "group":"Национални","logo":""},
  "BTV +48 LQ":{"id":"BTV +48 LQ", "group":"Национални","logo":""},
  "Nova +48 LQ":{"id":"Nova +48 LQ", "group":"Национални","logo":""}
}