# -*- coding: utf-8 -*-
### mapping for all possible channels on earth :)

channels_map = {
  "БНТ 1":{"id":"BNT1","group":"Национални","logo":"http://logos.kodibg.org/bnt1.png"},
  "БНТ 2":{"id":"БНТ 2", "group":"Национални","logo":"http://logos.kodibg.org/bnt2.png"},
  "BNT1 HD":{"id":"BNT1", "group":"Национални","logo":"http://logos.kodibg.org/bnt1.png"},
  "БНТ 1 HD":{"id":"BNT1", "group":"Национални","logo":"http://logos.kodibg.org/bnt1.png"},
  "BNT World":{"id":"BNTWorld", "group":"Национални","logo":"http://logos.kodibg.org/bntworld.png"},
  "БНТ HD":{"id":"BNTHD", "group":"Спортни","logo":"http://logos.kodibg.org/bnthd.png"},
  "БНТ HD в SD":{"id":"BNTHD", "group":"Спортни","logo":"http://logos.kodibg.org/bnthd.png"},
  "bTV":{"id": "bTV","group":"Национални","logo": "http://logos.kodibg.org/btv.png"},
  "bTV HD":{"id":"bTV", "group":"Национални","logo":"http://logos.kodibg.org/btv.png"},
  "bTV Action HD":{"id":"bTVAction", "group":"Филми","logo":"http://logos.kodibg.org/btvaction.png"},
  "bTV Action":{"id":"bTVAction", "group":"Филми","logo":"http://logos.kodibg.org/btvaction.png"},
  "bTV Comedy":{"id":"bTVComedy", "group":"Филми","logo":"http://logos.kodibg.org/btvcomedy.png"},
  "bTV Cinema":{"id":"bTVCinema", "group":"Филми","logo":"http://logos.kodibg.org/btvcinema.png"},
  "bTV Lady":{"id":"bTVLady", "group":"Филми","logo":"http://logos.kodibg.org/btvlady.png"},
  "RING BG HD":{"id":"RING", "group":"Спортни","logo":"http://logos.kodibg.org/ring.png"},
  "Ring HD":{"id":"RING", "group":"Спортни","logo":"http://logos.kodibg.org/ring.png"},
  "Nova":{"id": "Nova","group":"Национални","logo": "http://logos.kodibg.org/novatv.png"},
  "Nova TV":{"id": "Nova","group":"Национални","logo": "http://logos.kodibg.org/novatv.png"},
  "KinoNova":{"id":"KinoNova", "group":"Филми","logo":"http://logos.kodibg.org/kinonova.png"},
  "Diema":{"id":"Diema", "group":"Филми","logo":"http://logos.kodibg.org/diema.png"},
  "Diema Family":{"id":"DiemaFamily", "group":"Филми","logo":"http://logos.kodibg.org/diemafamily.png"},
  "Diema Sport":{"id":"DiemaSport", "group":"Спортни","logo":"http://logos.kodibg.org/diemasport.png"},
  "Diema Sport HD":{"id":"DiemaSport", "group":"Спортни","logo":"http://logos.kodibg.org/diemasport.png"},
  "Diema Sport 2":{"id":"DiemaSport2", "group":"Спортни","logo":"http://logos.kodibg.org/diemasport2.png"},
  "Diema Sport 2 HD":{"id":"DiemaSport2", "group":"Спортни","logo":"http://logos.kodibg.org/diemasport2.png"},
  "Trace Sport Stars HD":{"id":"TraceSportStars", "group":"Спортни","logo":"http://logos.kodibg.org/tracesportstars.png"},  
  "Nova Sport":{"id":"NovaSport", "group":"Спортни","logo":"http://logos.kodibg.org/novasport.png"},
  "Nova Sport HD":{"id":"NovaSport", "group":"Спортни","logo":"http://www.vivacom.bg/web/files/richeditor/tv/tv-channels-logos/novasporthd.png"},
  "FOX":{"id":"FOX", "group":"Филми","logo":"http://logos.kodibg.org/fox.png"},
  "FOX HD":{"id":"FOX", "group":"Филми","logo":"http://logos.kodibg.org/fox.png"},
  "FOX Life":{"id":"FOXLife", "group":"Филми","logo":"http://logos.kodibg.org/foxlife.png"},
  "FOX Crime":{"id":"FOXCrime", "group":"Филми","logo":"http://logos.kodibg.org/foxcrime.png"},
  "FOX Channel":{"id":"FOXChannel", "group":"Филми","logo":"http://logos.kodibg.org/fox.png"},
  "FOX Life HD":{"id":"FOXLife", "group":"Филми","logo":""},
  "FOX Crime HD":{"id":"FOXCrime", "group":"Филми","logo":""},  
  "TV 1000":{"id":"TV1000", "group":"Филми","logo":"http://logos.kodibg.org/tv1000.png"},
  "TV1000":{"id":"TV1000", "group":"Филми","logo":"http://logos.kodibg.org/tv1000.png"},
  "DIVA Universal":{"id":"DIVA Universal", "group":"Национални","logo":"http://logos.kodibg.org/diva.png"},
  "AXN":{"id":"AXN", "group":"Филми","logo":"http://logos.kodibg.org/axn.png"},
  "AXN White":{"id":"AXNWhite", "group":"Филми","logo":"http://logos.kodibg.org/axnwhite.png"},
  "AXN Black":{"id":"AXNBlack", "group":"Филми","logo":"http://logos.kodibg.org/axnblack.png"},
  "Bulgaria on Air":{"id":"BulgariaOnAir", "group":"Национални","logo":"http://logos.kodibg.org/bgonair.png"},
  "BIT":{"id":"BiT", "group":"Национални","logo":"http://logos.kodibg.org/bit.png"},
  "BIT HD":{"id":"BiT", "group":"Национални","logo":"http://logos.kodibg.org/bit.png"},
  "ТВ Европа":{"id":"tveurope", "group":"Национални","logo":"http://logos.kodibg.org/tveuropa.png"},
  "Канал 0":{"id":"Kanal0", "group":"Регионални","logo":"http://logos.kodibg.org/kanal0.png"},
  "Kanal 0":{"id":"Kanal0", "group":"Регионални","logo":"http://logos.kodibg.org/kanal0.png"},
  "Канал 3":{"id":"Kanal3", "group":"Национални","logo":"http://logos.kodibg.org/kanal3.png"},
  "Kanal 3":{"id":"Kanal3", "group":"Национални","logo":"http://logos.kodibg.org/kanal3.png"},
  "Канал 4":{"id":"Kanal4", "group":"Регионални","logo":"http://logos.kodibg.org/kanal4.png"},  
  "Kanal 4":{"id":"Kanal4", "group":"Национални","logo":"http://logos.kodibg.org/kanal4.png"},
  "СКАТ":{"id":"Skat", "group":"Национални","logo":"http://logos.kodibg.org/skat.png"},
  "Skat":{"id":"Skat", "group":"Национални","logo":"http://logos.kodibg.org/skat.png"},
  "HMTV":{"id":"hmtv", "group":"Филми","logo":"http://logos.kodibg.org/hmtv.png"},
  "AMC":{"id":"AMC", "group":"Филми","logo":"http://logos.kodibg.org/amc.png"},
  "Bloomberg BG HD":{"id":"Bloomberg", "group":"Национални","logo":"http://logos.kodibg.org/bloombergtvbulgaria.png"},
  "Bloomberg BG":{"id":"BloombergBG", "group":"Национални","logo":"http://logos.kodibg.org/bloombergtvbulgaria.png"},
  "Bloomberg TV Bulgaria":{"id":"BloombergBG", "group":"Национални","logo":"http://logos.kodibg.org/bloombergtvbulgaria.png"},
  "Viasat Explorer":{"id":"ViasatExplorer", "group":"Документални","logo":"http://logos.kodibg.org/viasatexplorer.png"},
  "Viasat History":{"id":"ViasatHistory", "group":"Документални","logo":"http://logos.kodibg.org/viasathistory.png"},
  "Viasat HD":{"id":"Viasat Nature/History HD", "group":"Документални","logo":"http://logos.kodibg.org/viasathistory.png"},
  "Viasat Nature":{"id":"ViasatNature", "group":"Документални","logo":"http://logos.kodibg.org/viasathistory.png"},
  "Discovery HD":{"id":"DiscoveryHDShowcase", "group":"Документални","logo":"http://logos.kodibg.org/discoveryhdshowcase.png"},
  "Discovery Channel":{"id":"Discovery", "group":"Документални","logo":"http://logos.kodibg.org/discovery.png"},
  "Discovery Science":{"id":"DiscoveryScience", "group":"Документални","logo":"http://logos.kodibg.org/discoveryscience.png"},
  "Science":{"id":"DiscoveryScience", "group":"Документални","logo":"http://logos.kodibg.org/discoveryscience.png"},
  "Discovery World":{"id":"Discovery World", "group":"Документални","logo":"http://logos.kodibg.org/discoveryworld.png"},
  "Animal Planet":{"id":"AnimalPlanet", "group":"Документални","logo":"http://logos.kodibg.org/animalplanet.png"},
  "National Geographic":{"id":"National Geographic", "group":"Документални","logo":"http://logos.kodibg.org/natgeo.png"},
  "NGC HD":{"id":"NatGeo", "group":"Документални","logo":"http://logos.kodibg.org/natgeo.png"},
  "NatGeo HD":{"id":"NatGeo", "group":"Документални","logo":"http://logos.kodibg.org/natgeo.png"},
  "NatGeo Wild":{"id":"NatGeoWild", "group":"Документални","logo":"http://logos.kodibg.org/natgeowild.png"},
  "NatGeo Wild HD":{"id":"NatGeoWild", "group":"Документални","logo":"http://logos.kodibg.org/natgeowild.png"},
  "National Geogrphic WILD HD":{"id":"NatGeoWild", "group":"Документални","logo":"http://logos.kodibg.org/natgeowild.png"},
  "History Channel":{"id":"History", "group":"Документални","logo":"http://logos.kodibg.org/history.png"},
  "History Channel HD":{"id":"History", "group":"Документални","logo":"http://logos.kodibg.org/history.png"},
  "History HD":{"id":"History", "group":"Документални","logo":"http://logos.kodibg.org/history.png"},
  "History Channel HD":{"id":"History", "group":"Документални","logo":"http://logos.kodibg.org/history.png"},
  "History 2 HD":{"id":"H2 UK", "group":"Документални","logo":"http://3.bp.blogspot.com/-RzXst6jpzBw/Toi5hYDW9AI/AAAAAAAACPA/jFKuVx6JcaQ/s500/History+2+logo+2011.png"},
  "History Channel 2":{"id":"H2 UK", "group":"Документални","logo":"http://3.bp.blogspot.com/-RzXst6jpzBw/Toi5hYDW9AI/AAAAAAAACPA/jFKuVx6JcaQ/s500/History+2+logo+2011.png"},
  "Travel Channel HD":{"id":"TravelChannel", "group":"Документални","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/69315/2a00000152365a2740806ba6f25f1a22566c/z"},
  "Travel Channel":{"id":"TravelChannel", "group":"Документални","logo":"http://logos.kodibg.org/travelchannel.png"},
  "Travel HD":{"id":"TravelHD", "group":"Документални","logo":"http://logos.kodibg.org/traveltvhd.png"},
  "Travel TV HD":{"id":"TravelHD", "group":"Документални","logo":"http://logos.kodibg.org/traveltvhd.png"},
  "Travel TV":{"id":"TravelHD", "group":"Документални","logo":"http://logos.kodibg.org/traveltv.png"},
  "Travel HD в SD":{"id":"TravelHD", "group":"Документални","logo":"http://logos.kodibg.org/travelhd.png"},
  "TVT":{"id":"TVTTourism", "group":"Документални","logo":"http://logos.kodibg.org/tvt.png"},
  "TVT Tourism":{"id":"TVTTourism", "group":"Документални","logo":"http://logos.kodibg.org/tvt.png"},
  "От близо HD":{"id":"OtBlizoHD", "group":"Документални","logo":""},
  "DocuBox HD":{"id":"DocuBox", "group":"Документални","logo":"http://logos.kodibg.org/docubox.png"},
  "Wild TV HD":{"id":"WildTV", "group":"Документални","logo":""},
  "DTX":{"id":"DTX", "group":"Документални","logo":""},
  "C&I Networks":{"id":"vi", "group":"Документални","logo":"http://logos.kodibg.org/ci.png"},
  "Дестинация BG":{"id":"DestinationBG", "group":"Документални","logo":"http://logos.kodibg.org/destinationbg.png"},
  "Destination BG HD":{"id":"DestinationBG", "group":"Документални","logo":"http://logos.kodibg.org/destinationbg.png"},
  "Българска история HD":{"id":"BulHistory", "group":"Документални","logo":"http://logos.kodibg.org/bghistory.png"},
  "In LIFE TV":{"id":"inLife", "group":"Тематични","logo":""},
  "Hobby TV":{"id":"HobbyTV", "group":"Документални","logo":"http://logos.kodibg.org/hobbyhd.png"},
  "Hobby HD":{"id":"HobbyTVHD", "group":"Документални","logo":"http://logos.kodibg.org/hobbyhd.png"},
  "Hobby TV HD":{"id":"HobbyTVHD", "group":"Документални","logo":"http://logos.kodibg.org/hobbyhd.png"},
  "OutDoor HD":{"id":"OutDoor", "group":"Документални","logo":"http://logos.kodibg.org/outdoorchannel.png"},
  "BG Лов":{"id":"HobbyLovHD", "group":"Документални","logo":"http://logos.kodibg.org/hobbylov.png"},
  "Hobby lov HD":{"id":"HobbyLovHD", "group":"Документални","logo":"http://logos.kodibg.org/hobbylov.png"},
  "Animal Planet HD":{"id":"AnimalPlanet", "group":"Документални","logo":"http://logos.kodibg.org/animalplanet.png"},
  "Discovery Science HD":{"id":"DiscoveryScience", "group":"Документални","logo":"http://logos.kodibg.org/discoveryscience.png"},
  "Food Network":{"id":"FoodNetworkHD", "group":"Тематични","logo":"http://logos.kodibg.org/foodnetwork.png"},
  "Food Network HD":{"id":"FoodNetworkHD", "group":"Тематични","logo":"http://logos.kodibg.org/foodnetwork.png"},
  "Da Vinci Learning":{"id":"DaVinciLearning", "group":"Документални","logo":"http://logos.kodibg.org/davincilearning.png"},
  "The World":{"id":"TheWorld", "group":"Документални","logo":""},
  "Chasse & Peche":{"id":"ChassePeche", "group":"Документални","logo":""},
  "24 Техно":{"id":"24_techno", "group":"Документални","logo":""},
  "Wness HD":{"id":"Wness", "group":"Тематични","logo":"http://logos.kodibg.org/wnesstv.png"},
  "WNESS TV HD":{"id":"Wness", "group":"Тематични","logo":"http://logos.kodibg.org/wnesstv.png"},
  "Spark":{"id":"Spark", "group":"Документални","logo":""},
  "ID Xtra":{"id":"IDXtra", "group":"Документални","logo":"http://logos.kodibg.org/investigationdiscoveryxtra.png"},
  "24 Kitchen HD":{"id":"24Kitchen", "group":"Тематични","logo":"http://logos.kodibg.org/24kitchen.png"},
  "Fine Living":{"id":"FineLiving", "group":"Тематични","logo":"http://logos.kodibg.org/finelivingnetwork.png"},
  "24 Kitchen":{"id":"24Kitchen", "group":"Тематични","logo":"http://logos.kodibg.org/24kitchen.png"},
  "Kitchen":{"id":"24Kitchen", "group":"Тематични","logo":"http://logos.kodibg.org/24kitchen.png"},
  "Хайде в кухнята HD":{"id":"in_kitchen_hd", "group":"Тематични","logo":""},
  "Fiesta":{"id":"Fiesta", "group":"Тематични","logo":"http://logos.kodibg.org/fiestatv.png"},
  "Fiesta TV":{"id":"Fiesta", "group":"Тематични","logo":"http://logos.kodibg.org/fiestatv.png"},
  "TLC":{"id":"TLC", "group":"Филми","logo":"http://logos.kodibg.org/tlc.png"},
  "CBS Drama":{"id":"CBSDrama", "group":"Филми","logo":"http://logos.kodibg.org/cbsdrama.png"},
  "CBS Reality":{"id":"CBSReality", "group":"Филми","logo":"http://logos.kodibg.org/cbsreality.png"},
  "Comedy Central":{"id":"ComedyCentral", "group":"Филми","logo":"http://logos.kodibg.org/comedycentralextra.png"},
  "English Club":{"id":"EnglishClub", "group":"Национални","logo":""},
  "Movie Star":{"id":"MovieStar", "group":"Филми","logo":"http://logos.kodibg.org/moviestar.png"},
  "HBO":{"id":"HBO", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo.png"},
  "HBO HD":{"id":"HBO", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo.png"},
  "HBO 2":{"id":"HBO 2", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo.png2"},
  "HBO 2 HD":{"id":"HBO 2", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo2.png"},
  "HBO 3":{"id":"HBO 3", "group":"Национални","Филми":"http://logos.kodibg.org/tvbg/hbo3.png"},
  "HBO 3 HD":{"id":"HBO 3", "group":"Филми","logo":"http://logos.kodibg.org/tvbg/hbo3.png"},
  "Cinemax":{"id":"Cinemax", "group":"Филми","logo":"http://logos.kodibg.org/cinemax.png"},
  "Cinemax 2":{"id":"Cinemax 2", "group":"Филми","logo":"http://logos.kodibg.org/cinemax2.png"},
  "Cinemax HD":{"id":"Cinemax", "group":"Филми","logo":"http://logos.kodibg.org/cinemax.png"},
  "Cinemax 2 HD":{"id":"Cinemax 2", "group":"Филми","logo":"http://logos.kodibg.org/cinemax2.png"},
  "Deutsche Welle":{"id":"Deutsche Welle", "group":"Новини","logo":"http://logos.kodibg.org/deutschewelle.png"},
  "CNN International":{"id":"CNNInternational", "group":"Новини","logo":"http://logos.kodibg.org/cnn.png"},
  "CNN International HD":{"id":"CNN International HD", "group":"Новини","logo":"http://logos.kodibg.org/cnn.png"},
  "Euronews":{"id":"Euronews", "group":"Новини","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/9/94/Euronews_2016.png/revision/latest/scale-to-width-down/200?cb=20160517202021&format=webp"},
  "Bloomberg":{"id":"Bloomberg", "group":"Новини","logo":"http://vignette1.wikia.nocookie.net/logopedia/images/8/8e/BLOOMBERG_TV_2007.jpg"},
  "Sky News":{"id":"Sky News UK", "group":"Новини","logo":"http://www.coultersproperty.co.uk/wp-content/uploads/2014/09/sky-news-logo-370x229.jpg"},
  "BBC Worldnews":{"id":"BBC World News", "group":"Новини","logo":"http://static.bbcverticals.com/wwfeatures/tv/assets/logos/16x9/bbc-world-news.png"},
  "BBC World HD":{"id":"BBC World", "group":"Новини","logo":"http://static.bbcverticals.com/wwfeatures/tv/assets/logos/16x9/bbc-world-news.png"},
  "CNBC":{"id":"CNBC UK", "group":"Новини","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/b/ba/CNBC_3D_White.svg/revision/latest/scale-to-width-down/185?cb=20160609174747"},
  "France 24":{"id":"France 24", "group":"Новини","logo":""},
  "TV5":{"id":"TV5 Monde", "group":"Новини","logo":""},
  "TV5 Monde":{"id":"TV5 Monde", "group":"Новини","logo":""},
  "Al Jazeera":{"id":"Al Jazeera", "group":"Новини","logo":""},
  "Al Jazeera Eng":{"id":"Al Jazeera", "group":"Новини","logo":""},
  "France 2":{"id":"France 2 (Fr)", "group":"Новини","logo":""},
  "France 2 HD":{"id":"France 2 (Fr)", "group":"Новини","logo":""},
  "France 3 HD":{"id":"France 3 (Fr)", "group":"Новини","logo":""},
  "France 4 HD":{"id":"France 4 (Fr)", "group":"Новини","logo":""},
  "CCTV 4":{"id":"CCTV 4", "group":"Новини","logo":""},
  "CCTV News":{"id":"CCTV News", "group":"Новини","logo":""},
  "Russia Today":{"id":"Russia Today", "group":"Новини","logo":""},
  "RT News HD":{"id":"RT News HD", "group":"Документални","logo":""},
  "RT Docu HD":{"id":"Russia Today Documentary", "group":"Документални","logo":""},
  "NHK World HD":{"id":"NHK World UK", "group":"Новини","logo":""},
  "NHK World":{"id":"NHK World UK", "group":"Новини","logo":""},
  "CCTV 9 Documentary":{"id":"CCTV9 Documentary", "group":"Документални","logo":""},
  "ID Xtra HD":{"id":"ID Xtra HD", "group":"Документални","logo":""},
  "Discovery Turbo HD":{"id":"Discovery Turbo UK", "group":"Документални","logo":"http://vignette1.wikia.nocookie.net/logopedia/images/c/cb/Discovery_Turbo_2009.png/revision/latest/scale-to-width-down/300?cb=20100413144122&format=webp"},
  "PO TV":{"id":"POTV", "group":"Регионални","logo":"http://logos.kodibg.org/potv.png"},
  "PO TV Trakia":{"id":"POTV", "group":"Регионални","logo":"http://logos.kodibg.org/potv.png"},
  "Черно море":{"id":"ChernoMore", "group":"Регионални","logo":"http://logos.kodibg.org/chernomore.png"},
  "VTV":{"id":"VTV", "group":"Национални","logo":"http://logos.kodibg.org/vtv.png"},
  "BG DNES":{"id":"BGDNES", "group":"Документални","logo":"http://logos.kodibg.org/bgdnestv.png"},
  "BG DNES HD":{"id":"BGDNES", "group":"Документални","logo":"http://logos.kodibg.org/bgdnestv.png"},
  "Bulgaria 24":{"id":"Bulgaria24", "group":"Национални","logo":"http://logos.kodibg.org/bulgaria24.png"},
  "Varna TV":{"id":"VarnaTV", "group":"Регионални","logo":"http://logos.kodibg.org/tvvarna.png"},
  "Стойчев":{"id":"Stoichev", "group":"Регионални","logo":"http://logos.kodibg.org/tvstoichev.png"},
  "Stoychev HD":{"id":"Stoichev", "group":"Регионални","logo":"http://logos.kodibg.org/tvstoichev.png"},
  "TV Stara Zagora":{"id":"tvstz", "group":"Регионални","logo":"http://logos.kodibg.org/tvstz.png"},
  "TV Zagora":{"id":"tvstz", "group":"Регионални","logo":"http://logos.kodibg.org/tvzagora.png"},
  "КИС 13":{"id":"kiss13", "group":"Регионални","logo":"http://logos.kodibg.org/kiss13.png"},
  "БНП ТВ":{"id":"БНП ТВ", "group":"Национални","logo":"http://logos.kodibg.org/bnptv.png"},
  "Agro TV":{"id":"AgroTV", "group":"Национални","logo":"http://logos.kodibg.org/agrotv.png"},
  "Alfa TV":{"id":"Alfa", "group":"Национални","logo":"http://logos.kodibg.org/alfa.png"},
  "Alfa":{"id":"Alfa", "group":"Национални","logo":"http://logos.kodibg.org/alfa.png"},
  "TV1":{"id":"TV1", "group":"Национални","logo":"http://logos.kodibg.org/tv1.png"},
  "TV1 HD":{"id":"TV1", "group":"Национални","logo":"http://logos.kodibg.org/tv1.png"},
  "TV 1 HD":{"id":"TV1", "group":"Национални","logo":"http://logos.kodibg.org/tv1.png"},
  "100% Auto Moto TV":{"id":"AutoMotorSport", "group":"Спортни","logo":"http://logos.kodibg.org/automoto.png"},
  "ВТК":{"id":"ВТК", "group":"Национални","logo":"http://logos.kodibg.org/vtk.png"},
  "Евроком":{"id":"Eurocom", "group":"Национални","logo":"http://logos.kodibg.org/evrokom.png"},
  "Evrokom":{"id":"Eurocom", "group":"Национални","logo":"http://logos.kodibg.org/evrokom.png"},
  "БХ ТВ":{"id":"БХ ТВ", "group":"Национални","logo":"http://logos.kodibg.org/bhtv.png"},
  "BHTV":{"id":"БХ ТВ", "group":"Национални","logo":"http://logos.kodibg.org/bhtv.png"},
  "ПП ТВ":{"id":"ПП ТВ", "group":"Национални","logo":"http://logos.kodibg.org/pptv.png"},  
  "Еврошанс":{"id":"Еврошанс", "group":"Спортни","logo":""},
  "Fishing & Hunting":{"id":"FishingHunting", "group":"Документални","logo":"http://logos.kodibg.org/thefishinghuntingchannel.png"},
  "BG Info":{"id":"BG Info", "group":"Документални","logo":"http://logos.kodibg.org/bginfo.png"},
  "HMTV HD":{"id":"HMTV HD", "group":"Документални","logo":"http://logos.kodibg.org/hmtv.png"},
  "M1":{"id":"M1", "group":"Музикални","logo":""},
  "M2":{"id":"M2", "group":"Музикални","logo":""},
  "Music Box (Укр)":{"id":"Music Box (Укр)", "group":"Музикални","logo":""},
  "Джус ТВ":{"id":"Джус ТВ", "group":"Музикални","logo":""},  
  "Vevo HD":{"id":"Vevo HD", "group":"Музикални","logo":""},
  "Djazz HD":{"id":"Djazz HD", "group":"Музикални","logo":""},
  "Brava HD":{"id":"Brava HD", "group":"Музикални","logo":""},
  "Classica HD":{"id":"Classica HD", "group":"Музикални","logo":"http://logos.kodibg.org/classica.png"},
  "Fen Folk":{"id":"FenFolk", "group":"Музикални","logo":"http://logos.kodibg.org/fenfolk.png"},
  "Fen Folk TV":{"id":"FenFolk", "group":"Музикални","logo":"http://logos.kodibg.org/fenfolk.png"},
  "FEN HD":{"id":"FENTV", "group":"Музикални","logo":"http://logos.kodibg.org/fentv.png"},
  "Hit Mix Channel":{"id":"Hit Mix Channel", "group":"Музикални","logo":"http://logos.kodibg.org/hitmix.png"},
  "Фолклор HD":{"id":"FolklorTV", "group":"Музикални","logo":"http://logos.kodibg.org/folklortv.png"},
  "Balkanika HD":{"id":"Balkanika", "group":"Музикални","logo":"http://logos.kodibg.org/balkanika.png"},
  "Balkanica HD":{"id":"Balkanika", "group":"Музикални","logo":"http://logos.kodibg.org/balkanika.png"},
  "BG Music HD":{"id":"BGMusicChannel", "group":"Музикални","logo":"http://logos.kodibg.org/bgmusicchannel.png"},
  "Roma TV":{"id":"roma_tv", "group":"Музикални","logo":""},
  "Roma TV HD":{"id":"roma_tv", "group":"Музикални","logo":""},
  "iConcerts HD":{"id":"iConcerts", "group":"Музикални","logo":"http://logos.kodibg.org/iconcerts.png"},
  "MTV Dance":{"id":"MTVDance", "group":"Музикални","logo":"http://logos.kodibg.org/mtvdance.png"},
  "MTV Live HD":{"id":"MTVLiveHD", "group":"Музикални","logo":"http://logos.kodibg.org/mtvlivehd.png"},
  "MTV":{"id":"MTV", "group":"Музикални","logo":"http://logos.kodibg.org/mtv.png"},
  "MTV Rocks":{"id":"MTVRocks", "group":"Музикални","logo":"http://logos.kodibg.org/mtvrocks.png"},
  "MTV Hits":{"id":"MTVhits", "group":"Музикални","logo":"http://logos.kodibg.org/mtvhits.png"},
  "VH1":{"id":"VH1", "group":"Музикални","logo":"http://logos.kodibg.org/vh1.png"},
  "VH1 Classic":{"id":"VH1 Classic", "group":"Музикални","logo":"http://logos.kodibg.org/vh1classic.png"},
  "Mezzo":{"id":"mezzo", "group":"Музикални","logo":"http://logos.kodibg.org/mezzo.png"},
  "Mezzo Live HD":{"id":"Mezzo Live HD", "group":"Музикални","logo":"http://logos.kodibg.org/mezzolivehd.png"},
  "Fast&amp;FunBox HD":{"id":"FastnFunBoxHD", "group":"Тематични","logo":"http://logos.kodibg.org/fastandfunbox.png"},
  "Fashion TV":{"id":"FashionTV", "group":"Тематични","logo":"http://logos.kodibg.org/fashiontv.png"},
  "Fashion One HD":{"id":"FashionOneHD", "group":"Тематични","logo":"http://logos.kodibg.org/fashionone.png"},
  "Fashion HD":{"id":"FashionTV", "group":"Тематични","logo":"http://logos.kodibg.org/fashiontv.png"},
  "FashionBox HD":{"id":"FashionBox", "group":"Тематични","logo":"http://logos.kodibg.org/fashionbox.png"},
  "Smash Hits":{"id":"Smash Hits", "group":"Музикални","logo":""},
  "F.O. HD":{"id":"F.O. HD", "group":"Тематични","logo":""},
  "Body and Balance":{"id":"Body and Balance", "group":"Тематични","logo":""},
  "World Fashion HD":{"id":"World Fashion HD", "group":"Тематични","logo":""},
  "F.O. TV":{"id":"F.O. TV", "group":"Тематични","logo":""},
  "Deluxe Lounge HD":{"id":"DeluxeLoungeHD", "group":"Тематични","logo":"http://logos.kodibg.org/deluxeloungehd.png"},
  "Luxe HD":{"id":"Luxe HD", "group":"Тематични","logo":""},
  "BG Music":{"id":"BGMusicChannel", "group":"Музикални","logo":"http://logos.kodibg.org/bgmusicchannel.png"},
  "The Voice":{"id":"TheVoice", "group":"Музикални","logo":"http://logos.kodibg.org/thevoicetv.png"},
  "City TV":{"id":"City", "group":"Музикални","logo":"http://logos.kodibg.org/citytv.png"},
  "359TV HD":{"id":"359TV", "group":"Музикални","logo":"http://logos.kodibg.org/359tv.png"},
  "Родина ТВ":{"id":"Родина ТВ", "group":"Музикални","logo":"http://logos.kodibg.org/rodinatv.png"},
  "BOX":{"id":"BoxTV", "group":"Музикални","logo":"http://logos.kodibg.org/boxtv.png"},
  "BOX HD":{"id":"BoxTV", "group":"Музикални","logo":"http://logos.kodibg.org/boxtv.png"},
  "BOX TV HD":{"id":"BoxTV", "group":"Музикални","logo":"http://logos.kodibg.org/boxtv.png"},
  "Kiss TV":{"id":"Kiss TV", "group":"Музикални","logo":""},
  "Juce TV":{"id":"Juce TV", "group":"Музикални","logo":""},
  "Deluxe Music":{"id":"DEDeluxeMusic", "group":"Музикални","logo":"http://logos.kodibg.org/deluxemusic.png"},
  "Deluxe Music HD":{"id":"DEDeluxeMusic", "group":"Музикални","logo":"http://logos.kodibg.org/deluxemusic.png"},
  "Magic TV":{"id":"MagicTV", "group":"Музикални","logo":"http://logos.kodibg.org/magictv.png"},
  "Планета":{"id":"Planeta", "group":"Музикални","logo":"http://logos.kodibg.org/planetatv.png"},
  "Планета HD":{"id":"PlanetaHD", "group":"Музикални","logo":"http://logos.kodibg.org/planetahd.png"},
  "Planeta":{"id":"Planeta", "group":"Музикални","logo":"http://logos.kodibg.org/planetahd.png"},
  "Planeta HD":{"id":"PlanetaHD", "group":"Музикални","logo":"http://logos.kodibg.org/planetahd.png"},
  "Планета Фолк":{"id":"PlanetaFolk", "group":"Музикални","logo":"http://logos.kodibg.org/planetafolk.png"},
  "FEN TV":{"id":"FENTV", "group":"Музикални","logo":"http://logos.kodibg.org/fentv.png"},
  "Fen TV HD":{"id":"FENTV", "group":"Музикални","logo":"http://logos.kodibg.org/fentv.png"},
  "Balkanika":{"id":"Balkanika", "group":"Музикални","logo":"http://logos.kodibg.org/balkanika.png"},
  "DSTV":{"id":"DSTV", "group":"Музикални","logo":"http://logos.kodibg.org/dstv.png"},
  "Фолклор ТВ":{"id":"FolklorTV", "group":"Музикални","logo":"http://logos.kodibg.org/folklortv.png"},
  "Тянков HD":{"id":"TiankovFolk", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},
  "Tiankov Folk HD":{"id":"TiankovFolk", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},
  "Тянков Мюзик HD":{"id":"TiankovFolk", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},
  "Тянков ТВ":{"id":"TiankovFolk", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},
  "Tiankov Music":{"id":"TiankovMusic", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovpop.png"},  
  "Tiankov Orient HD":{"id":"TiankovOrient", "group":"Музикални","logo":"http://logos.kodibg.org/tiankovorientfolk.png"},  
  "Salsa+":{"id":"Salsa+", "group":"Музикални","logo":""},
  "DM Sat":{"id":"DMSat", "group":"Музикални","logo":"http://logos.kodibg.org/dmsat.png"},
  "BN Music":{"id":"BN Music", "group":"Музикални","logo":""},
  "Shanson":{"id":"Шансон-TB", "group":"Музикални","logo":"http://avatars.mds.yandex.net/get-tv-shows/28886/2a0000015185956a9e522ce9cb22943cdf68/orig"},
  "Музыка":{"id":"Музыка", "group":"Музикални","logo":"http://avatars.mds.yandex.net/get-tv-shows/51765/2a000001518595a5d3a217801b307dfbb354/orig"},
  "Music Box Russia":{"id":"Music Box RU", "group":"Музикални","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/27485/2a000001519dc7f084e43d30ccdff14fb6b9/z"},
  "RCK":{"id":"RCK", "group":"Музикални","logo":""},
  "Jukebox":{"id":"Jukebox", "group":"Музикални","logo":""},
  "KCN Music 2":{"id":"KCN Music 2", "group":"Музикални","logo":""},
  "Super 7":{"id":"Super 7", "group":"Детски","logo":""},
  "Cartoon Network / TCM":{"id":"CartoonNetwork", "group":"Детски","logo":"http://logos.kodibg.org/cartoonnetwork.png"},
  "CN":{"id":"CartoonNetwork", "group":"Детски","logo":"http://logos.kodibg.org/cartoonnetwork.png"},
  "Boomerang":{"id":"Boomerang", "group":"Детски","logo":"http://logos.kodibg.org/boomerang.png"},
  "Fix and Foxi":{"id":"Fix and Foxi", "group":"Детски","logo":""},
  "Fix&amp;Foxi":{"id":"Fix and Foxi", "group":"Детски","logo":""},
  "eKids":{"id":"eKids", "group":"Детски","logo":"http://logos.kodibg.org/ekids.png"},
  "Nickelodeon":{"id":"Nickelodeon", "group":"Детски","logo":"http://logos.kodibg.org/nickelodeon.png"},
  "Nickelodeon HD":{"id":"nickelodeon_hd", "group":"Детски","logo":"http://logos.kodibg.org/nickelodeon.png"},
  "Nick Jr.":{"id":"NickJr", "group":"Детски","logo":"http://logos.kodibg.org/nickjr.png"},
  "KiKa HD":{"id":"KiKa HD", "group":"Детски","logo":""},
  "Baby TV":{"id":"BabyTV", "group":"Детски","logo":"http://logos.kodibg.org/babytv.png"},
  "Duck TV":{"id":"DuckTV", "group":"Детски","logo":"http://logos.kodibg.org/ducktv.png"},
  "Duck HD":{"id":"DuckTV", "group":"Детски","logo":"http://logos.kodibg.org/ducktv.png"},
  "Jim Jam":{"id":"JimJam", "group":"Детски","logo":"http://logos.kodibg.org/jimjam.png"},
  "Smile Of A Child":{"id":"Smile Of A Child", "group":"Детски","logo":""},
  "Disney channel":{"id":"Disney", "group":"Детски","logo":"http://logos.kodibg.org/disney.png"},
  "Disney Jr.":{"id":"DisneyJunior", "group":"Детски","logo":"http://logos.kodibg.org/disneyjunior.png"},
  "Disney Cinemagic HD":{"id":"Disney Cinemagic HD", "group":"Детски","logo":""},
  "Disney TR":{"id":"Disney TR", "group":"Детски","logo":""},
  "Карусель":{"id":"karusel", "group":"Детски","logo":""},
  "Детский мир":{"id":"Детский мир", "group":"Детски","logo":""},
  "Детский мир / Телеклуб":{"id":"Детский мир", "group":"Детски","logo":""},
  "Тест: Disney RU":{"id":"Тест: Disney RU", "group":"Детски","logo":""},
  "RiC":{"id":"RiC", "group":"Детски","logo":""},
  "Veronica / Disney (NL)":{"id":"Veronica / Disney (NL)", "group":"Детски","logo":""},
  "Pink Kids":{"id":"Pink Kids", "group":"Детски","logo":""},
  "Cartoon TR":{"id":"Cartoon TR", "group":"Детски","logo":""},
  "TRT Cocuk":{"id":"TRT Cocuk", "group":"Детски","logo":""},
  "Planet Cocuk":{"id":"Planet Cocuk", "group":"Детски","logo":""},
  "ERT":{"id":"ERT", "group":"Детски","logo":""},
  "Armenia":{"id":"Армения ТВ", "group":"Тематични","logo":""},
  "Armenia 1":{"id":"Armenia 1", "group":"Тематични","logo":"https://upload.wikimedia.org/wikipedia/commons/c/c3/Public_Television_of_Armenia_logo.jpg"},
  "RT Spanish HD":{"id":"RT Spanish HD", "group":"Новини","logo":"https://armeniagogo.com/wp-content/uploads/2016/08/armenia-tv-e1471512329713.png"},
  "Polonia":{"id":"Polonia", "group":"Тематични","logo":""},
  "TVR International":{"id":"TVR International", "group":"Тематични","logo":""},
  "RTP International":{"id":"rtp_int", "group":"Тематични","logo":""},
  "RTP Int":{"id":"rtp_int", "group":"Тематични","logo":""},
  "RTVE":{"id":"RTVE", "group":"Тематични","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Logo_RTVE.svg/130px-Logo_RTVE.svg.png"},
  "TVE":{"id":"TVE", "group":"Тематични","logo":"https://upload.wikimedia.org/wikipedia/commons/7/7b/TVE_logos.png"},
  "Slovenija 2 TV":{"id":"SLO 2", "group":"Тематични","logo":"http://vignette3.wikia.nocookie.net/logopedia/images/f/fc/TV_SLO_2.svg/revision/latest/scale-to-width-down/196?cb=20130317220600"},
  ### Италиански
  "RAI News":{"id":"RAI News", "group":"Италиански","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/RAI_News_2010_neu_Logo.svg/320px-RAI_News_2010_neu_Logo.svg.png"},
  "RAI 1":{"id":"RAI 1 IT", "group":"Италиански","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Rai_1_logo.svg/318px-Rai_1_logo.svg.png"},
  "Rai Uno":{"id":"RAI 1 IT", "group":"Италиански","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Rai_1_logo.svg/318px-Rai_1_logo.svg.png"},
  "RAI 2":{"id":"RAI 2 IT", "group":"Италиански","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Rai_2_logo.svg/320px-Rai_2_logo.svg.png"},
  "RAI 3":{"id":"RAI 3 IT", "group":"Италиански","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Rai_3.png/320px-Rai_3.png"},
  "RAI Scuola":{"id":"RAI Scuola", "group":"Италиански","logo":""},
  "RAI 1 HD":{"id":"RAI 1 IT", "group":"Италиански","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rai_1_HD_Logo.svg/287px-Rai_1_HD_Logo.svg.png"},
  "RAI 2 HD":{"id":"RAI 2 IT", "group":"Италиански","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Rai_2_HD_Logo.svg/320px-Rai_2_HD_Logo.svg.png"},
  "RAI 3 HD":{"id":"RAI 3 IT", "group":"Италиански","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Rai_3_HD_Logo.svg/320px-Rai_3_HD_Logo.svg.png"},
  "RAI Sport 1":{"id":"RAI Sport 1 IT", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Rai_Sport_1_2010.svg/577px-Rai_Sport_1_2010.svg.png"},
  "RAI Sport 1 HD":{"id":"RAI Sport 1 IT", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Rai_Sport_1_2010.svg/577px-Rai_Sport_1_2010.svg.png"},
  "RAI Sport 2":{"id":"RAI Sport 2 ИТ", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/RAI_Sport_2_2010_neu_Logo.svg/320px-RAI_Sport_2_2010_neu_Logo.svg.png"}, 
  ### Немски
  "Tagesschau 24":{"id":"tagesschau24", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Tagesschau24-2012.svg/301px-Tagesschau24-2012.svg.png"},
  "Tagesschau 24 HD":{"id":"tagesschau24", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Tagesschau24HD.svg/799px-Tagesschau24HD.svg.png"},
  "ORF1":{"id":"ORF 1", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/ORF1_logo.svg/320px-ORF1_logo.svg.png"},
  "ORF1 HD":{"id":"ORF 1", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/ORF_HD.svg/320px-ORF_HD.svg.png"},
  "ORF2":{"id":"ORF 2", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/ORF2_logo_n.svg/320px-ORF2_logo_n.svg.png"},
  "ORF2 HD":{"id":"ORF 2", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/ORF_2_HD_logo.svg/320px-ORF_2_HD_logo.svg.png"},
  "RTL":{"id":"RTL DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Rtl-logo.svg/320px-Rtl-logo.svg.png"},
  "RTL HD":{"id":"RTL DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/c/c3/RTL_HD_Logo.png"},
  "RTL 2":{"id":"RTL 2 DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/RTL2_Logo.svg/254px-RTL2_Logo.svg.png"},
  "RTL 2 HD":{"id":"RTL 2 DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/RTL_2_HD.svg/320px-RTL_2_HD.svg.png"},
  "RTL Nitro":{"id":"RTL NITRO", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/RTL_Nitro_logo.svg/320px-RTL_Nitro_logo.svg.png"},
  "RTL Nitro HD":{"id":"RTL NITRO", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/RTL_Nitro_HD.svg/320px-RTL_Nitro_HD.svg.png"},
  "Super RTL":{"id":"Super RTL DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Super_RTL_logo_2013.svg/320px-Super_RTL_logo_2013.svg.png"},
  "SAT1":{"id":"Sat.1 DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/SAT.1_Logo_2016.png/320px-SAT.1_Logo_2016.png"},
  "Sat.1 Gold":{"id":"SAT.1Gold", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Logo_Sat1_Gold_HD.svg/320px-Logo_Sat1_Gold_HD.svg.png"},
  "PRO7":{"id":"ProSieben DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/ProSieben_logo.svg/240px-ProSieben_logo.svg.png"},
  "Pro 7 HD":{"id":"ProSieben DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/ProSieben_HD_Logo.svg/320px-ProSieben_HD_Logo.svg.png"},
  "Kabel1":{"id":"Kabel Eins DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Kabel_eins_Logo_2015.svg/320px-Kabel_eins_Logo_2015.svg.png"},
  "Kabeleins":{"id":"Kabel Eins DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Kabel_eins_Logo_2015.svg/320px-Kabel_eins_Logo_2015.svg.png"},
  "VOX":{"id":"VOX DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/VOX.svg/320px-VOX.svg.png"},
  "3sat":{"id":"3sat DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/3sat-Logo.svg/320px-3sat-Logo.svg.png"},
  "3sat HD":{"id":"3sat DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/3sat_HD.svg/320px-3sat_HD.svg.png"},
  "Anixe HD":{"id":"ANIXE HD", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/5/55/ANIXE_HD_SERIE_Logo_2016.png"},
  "N24":{"id":"N24", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/c/ce/N24_Logo_2016.png"},
  "WDR":{"id":"WDR", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/WDR_Dachmarke.svg/320px-WDR_Dachmarke.svg.png"},
  "WDR HD":{"id":"WDR", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/WDR_HD.svg/300px-WDR_HD.svg.png"},
  "Arte HD":{"id":"Arte DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Arte_HD_Logo.svg/320px-Arte_HD_Logo.svg.png"},
  "Arte DE":{"id":"Arte DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Arte-Logo.svg/341px-Arte-Logo.svg.png"},
  "ARD / Das Erste HD":{"id":"ARD", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/7/7b/ARD_logo.png"},
  "ARD HD":{"id":"ARD", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/7/7b/ARD_logo.png"},
  "ZDF":{"id":"ZDF DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/ZDF-InfoKanal-Logo.svg/320px-ZDF-InfoKanal-Logo.svg.png"},
  "ZDF HD":{"id":"ZDF DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/ZDF_HD_Logo.svg/320px-ZDF_HD_Logo.svg.png"},
  "ZDF Info HD":{"id":"ZDF Info HD", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/ZDF-InfoKanal-Logo.svg/320px-ZDF-InfoKanal-Logo.svg.png"},
  "ZDF Neo HD":{"id":"ZDF Neo HD", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Zdf_neo_hd.svg/320px-Zdf_neo_hd.svg.png"},
  "ZDF Kultur HD":{"id":"ZDF Kultur HD", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Zdf.kultur_logo.svg/320px-Zdf.kultur_logo.svg.png"},
  "Servus HD":{"id":"Servus HD", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/de/thumb/b/be/ServusTV.svg/320px-ServusTV.svg.png"},
  "Eins Festival":{"id":"EinsFestival", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Festival_Logo_2008.svg/320px-Festival_Logo_2008.svg.png"},
  "Eins Festival HD ":{"id":"EinsFestival", "group":"Филми","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Einsfestival_HD.svg/320px-Einsfestival_HD.svg.png"},
  "N-TV":{"id":"NTV", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/N-tv-Logo.svg/320px-N-tv-Logo.svg.png"},
  "N-TV HD":{"id":"NTV", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Logo-n-tv.svg/320px-Logo-n-tv.svg.png"},
  "Phoenix":{"id":"Phoenix", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Phoenix_Logo_2012.svg/320px-Phoenix_Logo_2012.svg.png"},
  "Discovery DE HD":{"id":"Discovery Channel DE", "group":"Немски","logo":"http://vignette3.wikia.nocookie.net/logopedia/images/4/49/Discovery_Channel_2009.png/revision/latest/scale-to-width-down/250"},
  "Nat Geo HD DE":{"id":"National Geographic DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/National_Geographic_Channel.svg/300px-National_Geographic_Channel.svg.png"},
  "Natgeo Wild EU HD":{"id":"Nat Geo Wild DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/5/53/Logo_Chaine_Nat_Geo_Wild.png"},
  "Sky Hits HD":{"id":"Sky HITS DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Sky_Cinema_Hits_HD_DE_Logo_2016.png/320px-Sky_Cinema_Hits_HD_DE_Logo_2016.png"},
  "Sky Action HD":{"id":"Sky Action DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Sky_Cinema_Action_HD_DE_Logo_2016.png/320px-Sky_Cinema_Action_HD_DE_Logo_2016.png"},
  "Sky Atlantic HD":{"id":"Sky Atlantic DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Sky_Atlantic_HD_DE_Logo_2015.png/800px-Sky_Atlantic_HD_DE_Logo_2015.png"},
  "Sky Cinema HD":{"id":"Sky Cinema DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Sky_Cinema_Action_HD_DE_Logo_2016.png/320px-Sky_Cinema_Action_HD_DE_Logo_2016.png"},
  "13th Street HD":{"id":"13th Street DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/13th_Street_Universal_HD.svg/247px-13th_Street_Universal_HD.svg.png"},
  "TNT Film":{"id":"TNT Film DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/f/ff/TNT_Film_Logo_2016.png"},
  "TNT Serie HD":{"id":"TNT Serie DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/TNT_Serie_HD_Logo_2016.png/308px-TNT_Serie_HD_Logo_2016.png"},
  "SyFy HD":{"id":"Syfy DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Syfy_Universal_%28cropped%29.png/320px-Syfy_Universal_%28cropped%29.png"},
  "MGM HD":{"id":"MGM DE", "group":"Немски","logo":"http://vignette3.wikia.nocookie.net/logopedia/images/6/62/MGM_HD_UK.png/revision/latest/scale-to-width-down/250"},
  "Eins Plus HD":{"id":"EinsPlus DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/EinsPlus_HD.png/320px-EinsPlus_HD.png"},
  "SR Fernsehen HD":{"id":"SR Fernsehen DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/SR_Fernsehen_HD_Logo.png/320px-SR_Fernsehen_HD_Logo.png"},
  "Sky 3D de":{"id":"Sky 3D DE", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Sky_3D_DE_Logo_2015.png/320px-Sky_3D_DE_Logo_2015.png"},
  "Sky 1":{"id":"Sky 1 UK", "group":"Немски","logo":"https://upload.wikimedia.org/wikipedia/commons/f/f4/Sky1_Germany_Logo_2016.png"},
  "Sky 2":{"id":"Sky 2 UK", "group":"Немски","logo":""},
  ###
  "Первый Инт. канал (тест)":{"id":"Первый Инт. канал (тест)", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/70764/2a000001518595815f61238b1893ded04218/orig"},
  "Первый канал (EUR)":{"id":"Первый канал. (Европа)", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/70764/2a000001518595815f61238b1893ded04218/orig"},
  "Первый канал HD (RU)":{"id":"Первый канал", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/28884/2a000001519dc87ac3990967fa54f2f9c24f/z"},
  "Perviy Kanal":{"id":"Первый канал", "group":"Руски","logo":"http://logos.kodibg.org/perviykanal.png"},
  "CTC Инт.":{"id":"CTC Инт.", "group":"Руски","logo":""},
  "TVCI Центр":{"id":"ТВН - ТВ Центр", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/54380/2a00000152365a117a5cd709422aa2fc3e78/z"},
  "ТНТ":{"id":"ТНТ", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/51765/2a00000151859591eb09e5597c7fbcdbe1bf/orig"},
  "RTVi":{"id":"RTVi", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/30293/2a0000015185959cee6b309c47fdae23f682/orig"},
  "Живи":{"id":"Живи", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/51763/2a000001518ea8c7d2ff182ec07d4a271408/z"},
  "Охота и рыбалка":{"id":"Ribalka", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/54381/2a00000151859598f0ab9e6578682e49f4c0/orig"},
  "Звезда +2":{"id":"Звезда", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/54380/2a000001519e859fc283780466ec027aff42/z"},
  "Россия HD":{"id":"Россия HD", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/30303/2a00000155c527833be3dc0c9c407edcc20b/z"},
  "TV RUS":{"id":"TV RUS", "group":"Руски","logo":""},
  "НТВ":{"id":"НТВ", "group":"Руски","logo":"http://img.teleguide.info/channel/4.gif"},
  "НТВ HD":{"id":"НТВ", "group":"Руски","logo":"http://img.teleguide.info/channel/4.gif"},
  "НТВ Мир":{"id":"НТВ-Мир", "group":"Руски","logo":"http://img.teleguide.info/channel/4.gif"},
  "Россия 24":{"id":"Россия 24", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/27485/2a000001545169930632c1ca9db3b74aa1ea/160x160"},
  "Наше кино":{"id":"РТВ - Наше кино", "group":"Руски","logo":"http://img.teleguide.info/channel/447.gif"},
  "РТР Планета":{"id":"РТР Планета СНГ", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/27485/2a000001545d550433834a2ebde8e743b7bc/160x160"},
  "Дом кино":{"id":"Дом кино", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/70764/2a0000015185956841a817a916b658d42308/orig"},
  "Время":{"id":"Время", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/70764/2a000001518595866884f69cd950e9e99236/orig"},
  "Перец":{"id":"Перец", "group":"Руски","logo":""},
  "Телекафе":{"id":"Телекафе", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/30293/2a000001518595a59435fc2c1919813a5023/orig"},  
  "Тест: Первый канал  (RU)":{"id":"Тест: Первый канал  (RU)", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/70764/2a000001518595815f61238b1893ded04218/orig"},
  "Русский Экстрим":{"id":"Русский Экстрим", "group":"Спортни","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/27485/2a000001519edbb3b3475d2bf08e89e7c752/z"},
  "Мир ТВ":{"id":"Мир", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/51763/2a00000151868030b24d6fd2ec57683eb583/z"},
  "MirTv":{"id":"Мир", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/51763/2a00000151868030b24d6fd2ec57683eb583/z"},
  "ТБН Россия":{"id":"ТБН", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/51765/2a0000015185956c8c9007c533f5da45f798/orig"},
  "Наука 2.0":{"id":"Наука 2.0", "group":"Руски","logo":"http://img.teleguide.info/channel/300105.gif"},
  "Россия 1":{"id":"Россия 1", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/27487/2a000001518595a8811f57c67b2d17a3dd9b/orig"},
  "Russian Travel Guide":{"id":"Russian Travel Guide (RTG TV)", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/69315/2a0000015186d9e6fff87fe0f8258768cadb/z"},
  "Ю":{"id":"Ю", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/27485/2a000001519d87a29327a5797cbd3714e47f/z"},
  "Телеканал 2x2":{"id":"Телеканал 2x2", "group":"Руски","logo":""},
  "Наука":{"id":"Наука", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/38123/2a00000157b3d2439b72545f31c850123f04/160x160"},
  "Еврокино":{"id":"Еврокино", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/27485/2a000001519e3b531c7da8aa9328d1f0e6aa/z"},
  "Моя Планета":{"id":"Моя Планета", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/30293/2a00000151859585030e00fb3df1ac894046/orig"},
  "РЕН ТВ":{"id":"РЕН ТВ", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/27485/2a000001518f578d8f4c79b71c0938f3c124/z"},
  "FOX RU HD":{"id":"FOX RU HD", "group":"Руски","logo":"http://img.teleguide.info/channel/300010.gif"},
  "TV1000 Мегахит HD":{"id":"TV1000 Megahit HD", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/69315/2a00000152365a1559089e85546c42d66ae1/z"},
  "TV1000 Премиум HD":{"id":"TV1000 Premium HD", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/28884/2a00000152365a3bcd2bbfe2f232c6fd6803/z"},
  "TV1000 Комеди HD":{"id":"TV1000 Comedy HD", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/69315/2a00000152365a4fc25ff3256725ac9f018e/z"},
  "Тест: Русский Иллюзион":{"id":"Русский Иллюзион", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/70787/2a000001518642631913ba19d3ae51fd989c/z"},
  "Илюзион+":{"id":"Иллюзион +", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-shows/70764/2a0000015185959fff3bfe2c627f227796af/orig"},
  "СТС Россия":{"id":"СТС", "group":"Руски","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/28884/2a000001529cf4f20eb2544f89c006fafdf9/z"},
  "Интер (Укр)":{"id":"Интер (Укр)", "group":"Руски","logo":""},
  "1+1 (Укр)":{"id":"1+1 (Укр)", "group":"Руски","logo":""},
  "2+2 (Укр)":{"id":"2+2 (Укр)", "group":"Руски","logo":""},
  "ICTV (Укр)":{"id":"ICTV (Украина)", "group":"Руски","logo":"http://img.teleguide.info/channel/300059.gif"},
  "СТБ (Укр)":{"id":"СТБ", "group":"Руски","logo":"http://img.teleguide.info/channel/318.gif"},
  "НТН (Укр)":{"id":"НТН (Украина)", "group":"Руски","logo":"http://img.teleguide.info/channel/300062.gif"},
  "ТЕТ (Укр)":{"id":"ТЕТ", "group":"Руски","logo":"http://img.teleguide.info/channel/319.gif"},
  "Новый (Укр)":{"id":"Новый Канал", "group":"Руски","logo":"http://img.teleguide.info/channel/315.gif"},
  "112 HD (Укр)":{"id":"112 Украина", "group":"Руски","logo":""},
  "Телеканал новостей 24 (Укр)":{"id":"Телеканал новостей 24 (Укр)", "group":"Руски","logo":""},
  "5 канал (Укр)":{"id":"5 канал (Украина)", "group":"Руски","logo":"http://img.teleguide.info/channel/300058.gif"},
  "Тонис HD (Укр)":{"id":"Тонис", "group":"Руски","logo":"http://img.teleguide.info/channel/320.gif"},
  "HD Fashion (Укр)":{"id":"HD Fashion (Укр)", "group":"Руски","logo":""},
  "TF1 HD":{"id":"TF1 HD", "group":"Френски","logo":""},
  "La Une HD":{"id":"La Une HD", "group":"Френски","logo":""},
  "La Deux":{"id":"La Deux", "group":"Френски","logo":""},
  "La Trois":{"id":"La Trois", "group":"Френски","logo":""},
  "Club RTL":{"id":"Club RTL", "group":"Френски","logo":""},
  "Plug RTL":{"id":"Plug RTL", "group":"Френски","logo":""},
  "RTL TVi HD":{"id":"RTL TVi HD", "group":"Френски","logo":""},
  "Animaux":{"id":"Animaux", "group":"Френски","logo":""},
  "NT1":{"id":"NT1", "group":"Френски","logo":""},
  "France 24 FR":{"id":"France 24 FR", "group":"Френски","logo":""},
  "BFM HD":{"id":"BFM HD", "group":"Френски","logo":""},
  "CCTV French":{"id":"CCTV French", "group":"Френски","logo":""},
  "AB3":{"id":"AB3", "group":"Френски","logo":""},
  "Toute L'histoire":{"id":"Toute L'histoire", "group":"Френски","logo":""},
  "RTL 9 HD":{"id":"RTL9 (Fr)", "group":"Френски","logo":""},
  "BFM Business HD":{"id":"BFM Business HD", "group":"Френски","logo":""},
  "TV 5 Monde HD ":{"id":"TV 5 Monde HD ", "group":"Френски","logo":""},
  "Kanal 7 (tr)":{"id":"Kanal 7 (tr)", "group":"Турски","logo":""},
  "TRT 1":{"id":"TRT 1", "group":"Турски","logo":""},
  "Salon 1 HD":{"id":"Salon 1 HD", "group":"Турски","logo":""},
  "Salon 2 HD":{"id":"Salon 2 HD", "group":"Турски","logo":""},
  "Salon 3 HD":{"id":"Salon 3 HD", "group":"Турски","logo":""},
  "Kanal D":{"id":"Kanal D", "group":"Турски","logo":""},
  "Moviemax Premier 1 HD":{"id":"Moviemax Premier 1 HD", "group":"Турски","logo":""},
  "Rumeli TV":{"id":"Rumeli TV", "group":"Турски","logo":""},
  "Yaban TV":{"id":"Yaban TV", "group":"Турски","logo":""},
  "Flash TV":{"id":"Flash TV", "group":"Турски","logo":""},
  "TRT":{"id":"TRT", "group":"Турски","logo":""},
  "NTV Spor":{"id":"NTV Spor", "group":"Турски","logo":""},
  "TRT Spor":{"id":"TRT Spor", "group":"Турски","logo":""},
  "TRT Avaz":{"id":"TRT Avaz", "group":"Турски","logo":""},
  "TRT Arapca":{"id":"TRT Arapca", "group":"Турски","logo":""},
  "TRT Music":{"id":"TRT Music", "group":"Турски","logo":""},
  "Euro D":{"id":"euro_d", "group":"Турски","logo":""},
  "TRT Haber":{"id":"TRT Haber", "group":"Турски","logo":""},
  "NTV TR":{"id":"NTV TR", "group":"Турски","logo":""},
  "A Spor":{"id":"A Spor", "group":"Турски","logo":""},
  "A Spor HD":{"id":"A Spor HD", "group":"Турски","logo":""},
  "Star TV":{"id":"Star TV", "group":"Турски","logo":""},
  "Euro Star":{"id":"Euro Star", "group":"Турски","logo":""},
  "Kardelen":{"id":"Kardelen", "group":"Турски","logo":""},
  "Abant TV":{"id":"Abant TV", "group":"Турски","logo":""},
  "GTV Guneydogu TV":{"id":"GTV Guneydogu TV", "group":"Турски","logo":""},
  "Kanal 26 TR":{"id":"Kanal 26 TR", "group":"Турски","logo":""},
  "TV 8":{"id":"TV 8", "group":"Турски","logo":""},
  "Show TV":{"id":"Show TV", "group":"Турски","logo":""},
  "Show Turk":{"id":"Show TV", "group":"Турски","logo":""},
  "FOX TR":{"id":"FOX TR", "group":"Турски","logo":""},
  "ATV Avrupa":{"id":"ATV Avrupa", "group":"Турски","logo":""},
  "Haber Turk":{"id":"Haber Turk", "group":"Турски","logo":""},
  "Planet Turk":{"id":"Planet Turk", "group":"Турски","logo":""},
  "Kanal 5":{"id":"Kanal 5", "group":"Турски","logo":""},
  "A Haber":{"id":"A Haber", "group":"Турски","logo":""},
  "ATV HD":{"id":"ATV", "group":"Турски","logo":""},
  "ATV":{"id":"ATV", "group":"Турски","logo":""},
  "Semerkand  HD":{"id":"Semerkand  HD", "group":"Турски","logo":""},
  "Star TV HD":{"id":"Star TV HD", "group":"Турски","logo":""},
  "Beyaz TV HD":{"id":"Beyaz TV HD", "group":"Турски","logo":""},
  "CNN Turk":{"id":"CNN Turk", "group":"Турски","logo":""},
  "NTV Avrupa":{"id":"ntv_avrupa", "group":"Турски","logo":""},
  "Kanal t":{"id":"Kanal t", "group":"Турски","logo":""},
  "NR1 Turk HD":{"id":"NR1 Turk HD", "group":"Турски","logo":""},
  "Kral Pop":{"id":"Kral Pop", "group":"Турски","logo":""},
  "Kral TV":{"id":"Kral TV", "group":"Турски","logo":""},
  "Dream Turk":{"id":"Dream Turk", "group":"Турски","logo":""},
  "Dream TV":{"id":"Dream TV", "group":"Турски","logo":""},
  "Viva TR":{"id":"Viva TR", "group":"Турски","logo":""},
  "Planet Mutfak":{"id":"Planet Mutfak", "group":"Турски","logo":""},
  "Planet Pembe":{"id":"Planet Pembe", "group":"Турски","logo":""},
  "PPV Info":{"id":"PPV Info", "group":"Турски","logo":""},
  "PPV 1 (demo)":{"id":"PPV 1 (demo)", "group":"","logo":""},
  "PPV 2 (demo)":{"id":"PPV 2 (demo)", "group":"","logo":""},
  "PPV 3 (demo)":{"id":"PPV 3 (demo)", "group":"","logo":""},
  "PPV 4 (demo)":{"id":"PPV 4 (demo)", "group":"","logo":""},
  "PPV 5 (demo)":{"id":"PPV 5 (demo)", "group":"","logo":""},
  "PPV 6 (demo)":{"id":"PPV 6 (demo)", "group":"","logo":""},
  "Film+":{"id":"FilmPlus", "group":"Филми","logo":"http://logos.kodibg.org/filmplus.png"},
  "Film +":{"id":"FilmPlus", "group":"Филми","logo":"http://logos.kodibg.org/filmplus.png"},
  "Film+ HD":{"id":"FilmPlus", "group":"Филми","logo":"http://logos.kodibg.org/filmplus.png"},
  "Film + HD":{"id":"FilmPlus", "group":"Филми","logo":"http://logos.kodibg.org/filmplus.png"},
  "FilmBox Extra HD":{"id":"FilmBoXtraHD", "group":"Филми","logo":"http://logos.kodibg.org/filmboxextra.png"},
  "FilmBox Plus HD":{"id":"FilmBoxPlusHD", "group":"Филми","logo":"http://logos.kodibg.org/filmboxplus.png"},
  "FilmBoxPlus HD":{"id":"FilmBoxPlusHD", "group":"Филми","logo":"http://logos.kodibg.org/filmboxplus.png"},
  "FilmBox HD":{"id":"FilmBoxPlusHD", "group":"Филми","logo":"http://logos.kodibg.org/filmboxplus.png"},
  "FilmBox Arthouse":{"id":"FilmboxArthouseHD", "group":"Филми","logo":"http://logos.kodibg.org/filmboxarthouse.png"},
  "Action + HD":{"id":"ActionPlus", "group":"Филми","logo":"http://logos.kodibg.org/actionplus.png"},
  "Action+ HD":{"id":"ActionPlus", "group":"Филми","logo":"http://logos.kodibg.org/actionplus.png"},
  "Cinema+":{"id":"CinemaPlus", "group":"Филми","logo":"http://logos.kodibg.org/cinemaplus.png"},
  "Cinema+ HD":{"id":"CinemaPlus", "group":"Филми","logo":"http://logos.kodibg.org/cinemaplus.png"},
  "Cinema + HD":{"id":"CinemaPlus", "group":"Филми","logo":"http://logos.kodibg.org/cinemaplus.png"},
  "Comedy+":{"id":"ComedyPlus", "group":"Филми","logo":"http://logos.kodibg.org/comedyplus.png"},
  "Comedy +":{"id":"ComedyPlus", "group":"Филми","logo":"http://logos.kodibg.org/comedyplus.png"},
  "Comedy + HD":{"id":"ComedyPlus", "group":"Филми","logo":"http://logos.kodibg.org/comedyplus.png"},
  "and TV HD":{"id":"and TV HD", "group":"Холандски","logo":""},
  "RTL Z HD (NL)":{"id":"RTL Z HD (NL)", "group":"Холандски","logo":""},
  "NPO 1 (NL)":{"id":"NPO 1 (NL)", "group":"Холандски","logo":""},
  "NPO 2 (NL)":{"id":"NPO 2 (NL)", "group":"Холандски","logo":""},
  "NPO 3 (NL)":{"id":"NPO 3 (NL)", "group":"Холандски","logo":""},
  "RTL 4 NL":{"id":"RTL 4 NL", "group":"Холандски","logo":""},
  "RTL 5 NL":{"id":"RTL 5 NL", "group":"Холандски","logo":""},
  "RTL 7 HD (NL)":{"id":"RTL 7 HD (NL)", "group":"Холандски","logo":""},
  "Film1 Action NL":{"id":"Film1 Action NL", "group":"Холандски","logo":""},
  "Film1 Comedy Kids NL":{"id":"Film1 Comedy Kids NL", "group":"Холандски","logo":""},
  "Film1 Premiere NL":{"id":"Film1 Premiere NL", "group":"Холандски","logo":""},
  "SBS 6 (NL)":{"id":"SBS 6 (NL)", "group":"Холандски","logo":""},
  "TuneBox HD":{"id":"360TuneBoxHD", "group":"Тематични","logo":"http://logos.kodibg.org/360tunebox.png"},
  "Sky Action":{"id":"Sky Movies Action &amp; Adventure UK", "group":"Филми","logo":""},
  "Sky Comedy":{"id":"Sky Movies Comedy UK", "group":"Филми","logo":""},
  "Sky SciFi/Horror":{"id":"Sky Movies Sci-Fi &amp; Horror UK", "group":"Филми","logo":""},
  "Sky Select":{"id":"Sky Movies Select UK", "group":"Филми","logo":""},
  "Sky Family":{"id":"Sky Movies Family UK", "group":"Филми","logo":""},
  "Sky Premiere +1":{"id":"Sky Movies Premiere UK", "group":"Филми","logo":""},
  "Sky Drama":{"id":"Sky Movies Drama &amp; Romance UK", "group":"Филми","logo":""},
  "Movies 4 Men":{"id":"Movies 4 Men", "group":"Филми","logo":""},
  "Comedy Central UK":{"id":"Comedy Central UK", "group":"Филми","logo":""},
  "Sony Movie Channel":{"id":"Sony Movie Channel", "group":"Филми","logo":""},
  "БНТ1 LQ":{"id":"БНТ1", "group":"Национални","logo":""},
  "bTV LQ":{"id":"bTV", "group":"Национални","logo":""},
  "Nova LQ":{"id":"Nova", "group":"Национални","logo":""},
  "bTV Comedy LQ":{"id":"bTVComedy", "group":"Филми","logo":""},
  "bTV Cinema LQ":{"id":"bTVCinema", "group":"Филми","logo":""},
  "bTV Action LQ":{"id":"bTVAction", "group":"Филми","logo":""},
  "KinoNova LQ":{"id":"KinoNova", "group":"Филми","logo":""},
  "Diema LQ":{"id":"Diema", "group":"Филми","logo":""},
  "FOX Life LQ":{"id":"FOXLife", "group":"Филми","logo":""},
  "FOX Crime LQ":{"id":"FOXCrime", "group":"Филми","logo":""},
  "FOX LQ":{"id":"FOX", "group":"Филми","logo":""},
  "БНТ2 LQ":{"id":"BNT2", "group":"Национални","logo":""},
  "ТВ Европа LQ":{"id":"tveurope", "group":"Национални","logo":""},
  "NOVAsport LQ":{"id":"NOVAsport", "group":"Спортни","logo":""},
  "RING LQ":{"id":"RING", "group":"Спортни","logo":""},
  "Eurosport LQ":{"id":"Eurosport", "group":"Спортни","logo":""},
  "Eurosport 2 LQ":{"id":"Eurosport2", "group":"Спортни","logo":""},
  "Sport+ LQ":{"id":"SportPlusHD", "group":"Спортни","logo":""},
  "F+ LQ":{"id":"FPlus", "group":"Спортни","logo":""},
  "TV+ LQ":{"id":"TVPlus", "group":"Национални","logo":""},
  "Discovery LQ":{"id":"Discovery", "group":"Документални","logo":""},
  "Animal Planet LQ":{"id":"AnimalPlanet", "group":"Документални","logo":""},
  "Diema Family LQ":{"id":"DiemaFamily", "group":"Филми","logo":""},
  "BTV Lady LQ":{"id":"BTVLady", "group":"Филми","logo":""},
  "24 Kitchen LQ":{"id":"24Kitchen", "group":"Тематични","logo":""},
  "Diema Sport LQ":{"id":"DiemaSport", "group":"Спортни","logo":""},
  "Diema Sport 2 LQ":{"id":"DiemaSport2", "group":"Спортни","logo":""},
  "Cartoon Net LQ":{"id":"CartoonNet", "group":"Детски","logo":""},
  "Disney LQ":{"id":"Disney", "group":"Детски","logo":""},
  "NatGeo LQ":{"id":"NatGeo", "group":"Документални","logo":""},
  "TLC LQ":{"id":"TLC", "group":"Тематични","logo":""},
  "Hobby LQ":{"id":"Hobby", "group":"Документални","logo":""},
  "Travel LQ":{"id":"TravelHD", "group":"Документални","logo":""},
  "Hstory LQ":{"id":"Hstory", "group":"Документални","logo":""},
  "Diva LQ":{"id":"Diva", "group":"Тематични","logo":""},
  "City LQ":{"id":"City", "group":"Музикални","logo":""},
  "Planeta LQ":{"id":"Planeta", "group":"Музикални","logo":""},
  "Planeta Folk LQ":{"id":"PlanetaFolk", "group":"Музикални","logo":""},
  "DM SAT LQ":{"id":"DMSAT", "group":"Музикални","logo":""},
  "BG Music LQ":{"id":"BGMusic", "group":"Музикални","logo":""},
  "Balkanika LQ":{"id":"Balkanika", "group":"Музикални","logo":""},
  "Фолклор LQ":{"id":"Фолклор", "group":"Музикални","logo":""},
  "Arirang":{"id":"Arirang", "group":"Музикални","logo":""},
  ### Спортни
  "Eurosport HD":{"id":"Eurosport1", "group":"Спортни","logo":"http://www.vivacom.bg/web/files/richeditor/tv/tv-channels-logos/eurosport1-hd-logo.png"},
  "Eurosport 2 HD":{"id":"Eurosport2", "group":"Спортни","logo":"http://www.vivacom.bg/web/files/richeditor/tv/tv-channels-logos/eurosport2-hd-logo.png"},
  "Eurosport News":{"id":"Eurosport News", "group":"Спортни","logo":"http://corporate.eurosport.com/wp-content/uploads/2015/02/monogram_eurosport_news.jpg"},
  "Eurosport DE HD":{"id":"Eurosport 1 DE", "group":"Спортни","logo":"http://www.vivacom.bg/web/files/richeditor/tv/tv-channels-logos/eurosport1-hd-logo.png"},
  "Eurosport":{"id":"Eurosport1", "group":"Спортни","logo":"http://www.vivacom.bg/web/files/richeditor/tv/tv-channels-logos/eurosport1-logo.png"},
  "Eurosport 2":{"id":"Eurosport2", "group":"Спортни","logo":"http://www.vivacom.bg/web/files/richeditor/tv/tv-channels-logos/eurosport2-logo.png"},
  "Sport+ HD":{"id":"SportPlusHD", "group":"Спортни","logo":"http://logos.kodibg.org/sportplushd.png"},
  "F+":{"id":"FPlus", "group":"Спортни","logo":"http://logos.kodibg.org/fplus.png"},
  "TV+":{"id":"TVPlus", "group":"Национални","logo":"http://logos.kodibg.org/tvplus.png"},
  "Auto Motor Sport":{"id":"AutoMotorSport", "group":"Спортни","logo":"http://logos.kodibg.org/automotorsport.png"},
  "Auto Motor Sport HD":{"id":"AutoMotorSport", "group":"Спортни","logo":"http://logos.kodibg.org/automotorsport.png"},
  "AMS HD":{"id":"AutoMotorSport", "group":"Спортни","logo":"http://logos.kodibg.org/automotorsport.png"},
  "Мотоспорт HD":{"id":"MotoSportHD", "group":"Спортни","logo":"http://logos.kodibg.org/motosport.png"},
  "Sky Sport HD 1":{"id":"Sky Sport 1", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/de/thumb/6/6d/Sky_Sport_HD_1_off-air_2011.png/320px-Sky_Sport_HD_1_off-air_2011.png"},
  "Sky Sport HD 2":{"id":"Sky Sport 2", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/de/thumb/4/42/Sky_Sport_HD_2_off-air_2011.png/320px-Sky_Sport_HD_2_off-air_2011.png"},
  "Sky Sport Austria":{"id":"Sky Sport Austria DE", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Sky_Sport_Austria_Logo_2016.png/320px-Sky_Sport_Austria_Logo_2016.png"},
  "Sky Sport HD 3":{"id":"Sky Sport HD 3", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/0/03/Skysport3hd-ita_new.png"},
  "Sky Sport HD 4":{"id":"Sky Sport HD 4", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/8/85/Sky_Sport_%28Italy%29.png"},
  "Sky Sport HD 5":{"id":"Sky Sport HD 5", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/8/85/Sky_Sport_%28Italy%29.png"},
  "Sky Sport HD 6":{"id":"Sky Sport HD 6", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/8/85/Sky_Sport_%28Italy%29.png"},
  "Sky Bundesliga 1 HD":{"id":"Sky Fußball Bundesliga DE", "group":"Спортни","logo":"http://vignette3.wikia.nocookie.net/logopedia/images/5/59/Sky_Bundesliga.png"},
  "Sport1 US HD":{"id":"Sport1 US", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sport1us.png"},
  "Sport1+ HD":{"id":"Sport1+", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sport1.png"},
  "Arena Sport 1 (SRB)":{"id":"Arena Sport 1 (SRB)", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/5/5d/ArenaSport_1%282%29.gif"},
  "Arena Sport 2 (SRB)":{"id":"Arena Sport 2 (SRB)", "group":"Спортни","logo":"http://vignette1.wikia.nocookie.net/logopedia/images/4/46/ArenaSport_2.gif"},
  "Arena Sport 3 (SRB)":{"id":"Arena Sport 3 (SRB)", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/d/d2/ArenaSport_3.gif"},
  "Arena Sport 4 (SRB)":{"id":"Arena Sport 4 (SRB)", "group":"Спортни","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/3/36/ArenaSport_4.gif"},
  "Arena Sport 5 (SRB)":{"id":"Arena Sport 5 (SRB)", "group":"Спортни","logo":"http://tvprofil.net/img/kanali-logo/arenasport_5_logo.png"},
  "Arena Sport 1 HD (HR)":{"id":"Arena Sport 1 HR", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/5/5d/ArenaSport_1%282%29.gif"},
  "Arena Sport 2 HD (HR)":{"id":"Arena Sport 2 HR", "group":"Спортни","logo":"http://vignette1.wikia.nocookie.net/logopedia/images/4/46/ArenaSport_2.gif"},
  "Arena Sport 3 HD (HR)":{"id":"Arena Sport 3 HR", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/d/d2/ArenaSport_3.gif"},
  "Arena Sport 4 HD (HR)":{"id":"Arena Sport 4 HR", "group":"Спортни","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/3/36/ArenaSport_4.gif"},
  "Arena Sport 5 HD (HR)":{"id":"Arena Sport 5 HD (HR)", "group":"Спортни","logo":"http://tvprofil.net/img/kanali-logo/arenasport_5_logo.png"},
  "Fight World HD":{"id":"Fight World HD", "group":"Спортни","logo":"http://www.digitaltveurope.net/wp-content/uploads/2016/01/FIGHTCHANNEL-LOGO-251x300.png"},
  "FightBox HD":{"id":"FightBox", "group":"Спортни","logo":"http://logos.kodibg.org/fightbox.png"},
  "Fast and Fun HD":{"id":"Fast and Fun HD", "group":"Спортни","logo":""},
  "Sportal HD":{"id":"Sportaltv", "group":"Спортни","logo":"http://logos.kodibg.org/sportalbg.png"},
  "BT Sports 1 *":{"id":"BT Sport 1", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/6/68/BT_Sport_1_%28pre-launch%29.svg/revision/latest/scale-to-width-down/640?cb=20130806193244"},
  "BT Sports 2 *":{"id":"BT Sport 2", "group":"Спортни","logo":"http://vignette1.wikia.nocookie.net/logopedia/images/2/2c/BT_Sport_2_%28pre-launch%29.svg/revision/latest/scale-to-width-down/640?cb=20130806193300"},
  "Sky Sports 1":{"id":"Sky Sports 1 UK", "group":"Спортни","logo":"http://footballontv.com/img/channels/square-300/Sky-Sports-1.png"},
  "Sky Sports 2":{"id":"Sky Sports 2 UK", "group":"Спортни","logo":"http://footballontv.com/img/channels/square-300/Sky-Sports-2.png"},
  "Sky Sports 3":{"id":"Sky Sports 3 UK", "group":"Спортни","logo":"http://footballontv.com/img/channels/square-300/Sky-Sports-3.png"},
  "Sky Sports 4":{"id":"Sky Sports 4 UK", "group":"Спортни","logo":"http://footballontv.com/img/channels/square-300/Sky-Sports-4.png"},
  "Sky Sports 5":{"id":"Sky Sports 5 UK", "group":"Спортни","logo":"http://footballontv.com/img/channels/square-300/Sky-Sports-5.png"},
  "Sky Sports F1":{"id":"Sky Sports F1 UK", "group":"Спортни","logo":"https://pbs.twimg.com/profile_images/502483207267164160/wyV8wUFV.png"},
  "Sport Klub 1 HR":{"id":"Sport Klub 1 HR", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub1.png"},
  "Sport Klub 2 HR":{"id":"Sport Klub 2 HR", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub2.png"},
  "Sport Klub 3 HR":{"id":"Sport Klub 3", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub3.png"},
  "Sport Klub 1":{"id":"Sport Klub 1", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub1.png"},
  "Sport Klub 2":{"id":"Sport Klub 2", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub2.png"},
  "Sport Klub 3":{"id":"Sport Klub 3", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub3.png"},
  "Sport Klub 3 HD":{"id":"Sport Klub 3", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub3.png"},
  "Sport Klub 4":{"id":"Sport Klub 4", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub4.png"},
  "Sport Klub 5":{"id":"Sport Klub 5", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub5.png"},
  "Sport Klub 6":{"id":"Sport Klub 6", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/sportklub6.png"},
  "Nova Sport 2 HD (CZ)":{"id":"Nova Sport 2 HD (CZ)", "group":"Спортни","logo":"http://www.pcdays.cz/wp-content/uploads/2016/02/Nova_Sport_2HD.png"},
  "Supper Tennis HD":{"id":"Supper Tennis HD", "group":"Спортни","logo":"http://www.supertennis.tv/images/supertennis-logo-new.png"},
  "Racing UK HD":{"id":"Racing UK", "group":"Спортни","logo":"http://tv.sky.com/logo/248/60/skychb3636.png"},
  "Premier Sports HD":{"id":"Premier Sports", "group":"Спортни","logo":"http://tv.sky.com/logo/248/60/skychb5311.png"},
  "Premier Sports":{"id":"Premier Sports", "group":"Спортни","logo":"http://vignette1.wikia.nocookie.net/logopedia/images/d/d1/PremierSports2012.png"},
  "LIG TV":{"id":"Lig TV 1 (Tr)", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/f/f3/Lig-tv.png"},
  "LIG TV 2":{"id":"Lig TV 2 (Tr)", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/f/f3/Lig-tv.png"},
  "LIG TV 3":{"id":"Lig TV 3 (Tr)", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/f/f3/Lig-tv.png"},
  "Digi Sport 1":{"id":"Digi Sport 1", "group":"Спортни","logo":"http://vignette3.wikia.nocookie.net/logopedia/images/d/d5/Digi_sport1.png"},
  "Digi Sport 2":{"id":"Digi Sport 2", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/5/57/Digi_sport2.png"},
  "Digi Sport 3":{"id":"Digi Sport 3", "group":"Спортни","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/c/cb/Digi_sport3_hu.png"},
  "Digi Sport 4":{"id":"Digi Sport 4", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/5/53/DigiSport-SK-4_o_%281%29.jpg"},
  "Eurosport 360 HD 1":{"id":"Eurosport 360 HD 1", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Eurosport_360_Logo.svg/320px-Eurosport_360_Logo.svg.png"},
  "Eurosport 360 HD 2":{"id":"Eurosport 360 HD 2", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Eurosport_360_Logo.svg/320px-Eurosport_360_Logo.svg.png"},
  "Setanta":{"id":"Setanta Sports Ireland 1", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Setanta-logo.jpg/320px-Setanta-logo.jpg"},
  "Motors TV HD":{"id":"Motors UK", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Motors_TV_logo.svg/320px-Motors_TV_logo.svg.png"},
  "Motors UK":{"id":"Motors UK", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Motors_TV_logo.svg/320px-Motors_TV_logo.svg.png"},
  "Racing UK":{"id":"Racing UK", "group":"Спортни","logo":"https://uk.motorstv.com/sites/default/files/logo_motorstv_simple_0.png"},
  "Fuel TV HD":{"id":"Fuel TV HD", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/5/51/FUEL_TV_HD.png"},
  "Box Nation":{"id":"Box Nation UK", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/en/c/c8/BoxNation2014Logo.png"},
  "FOX Sports 1 NL":{"id":"FOX Sports 1 (Nl)", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports1.png"},
  "FOX Sports 2 NL":{"id":"FOX Sports 2 (Nl)", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports2.png"},
  "FOX Sports 3 NL":{"id":"FOX Sports 3 (Nl)", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports3.png"},
  "FOX Sports 4 NL":{"id":"FOX Sports 4 (Nl)", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports4.png"},
  "FOX Sports 5 NL":{"id":"FOX Sports 5 (Nl)", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports5.png"},
  "FOX Sports 6 NL":{"id":"FOX Sports 6 (Nl)", "group":"Спортни","logo":"http://logos.kodibg.org/tvbg/foxsports6.png"},  
  "beIN Sports 1 HD (fr)":{"id":"beIN Sport 1 (Fr)", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/9/92/BeIN_Sport_1_HD.jpg"},
  "beIN Sports 2 HD (fr)":{"id":"beIN Sport 2 (Fr)", "group":"Спортни","logo": "https://upload.wikimedia.org/wikipedia/commons/a/a8/BeIN_Sport_2_HD_logo.jpg"},
  "beIN Sports 3 HD (fr)":{"id":"beIN Sport 3 (Fr)", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/BeIN_Sports_3_HD.png/320px-BeIN_Sports_3_HD.png"},
  "beIN Sports 1 (ar)":{"id":"Bein Sports 1", "group":"Спортни","logo":"http://vignette3.wikia.nocookie.net/logopedia/images/0/03/BeIN_Sport_1_logo_in_Indonesia.png"},
  "beIN Sports 2 (ar)":{"id":"Bein Sports 2", "group":"Спортни","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/8/8f/BeIN_Sport_2_Indonesia.png"},
  "beIN Sports 3 (ar)":{"id":"Bein Sports 3", "group":"Спортни","logo":"http://vignette3.wikia.nocookie.net/logopedia/images/7/7c/BeIN_Sport_3_EPL.png"},
  "beIN Sports 4 (ar)":{"id":"Bein Sports 4", "group":"Спортни","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/c/c3/Bein_4.png"},
  "Bein Sports HD (es)":{"id":"Bein Sports HD (es)", "group":"Спортни","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/f/f6/BeIN_Sports.png"},
  "Canal+ Golf HD":{"id":"Canal+ Golf HD", "group":"Спортни","logo":"http://vignette2.wikia.nocookie.net/logopedia/images/e/ef/MovistarGolf.png"},
  "Canal+ Deportes HD":{"id":"Canal+ Deportes (Spa)", "group":"Спортни","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Canal%2B_Deportes_2008.svg/320px-Canal%2B_Deportes_2008.svg.png"},
  "Canal+ Toros HD":{"id":"Canal+ Toros HD", "group":"Спортни","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/c/c0/Toros_TV.png"},
  "Movistar F1 HD":{"id":"Movistar F1 HD", "group":"Филми","logo":"https://www.telefonica.com/documents/23283/951045/movistartv-f1_426.jpg"},
  "Movistar GP HD":{"id":"Movistar GP HD", "group":"Филми","logo":"http://i.blogs.es/14822e/logotipo_movistar_tv_motogp/1024_2000.jpg"},
  "Матч ТВ":{"id":"Матч ТВ", "group":"Спортни","logo":"http://logos.kodibg.org/matchtv.png"},
  "Матч! ТВ HD":{"id":"Матч ТВ", "group":"Спортни","logo":"http://logos.kodibg.org/matchtv.png"},
  "Матч! Футбол 1 HD":{"id":"МАТЧ! Футбол 1", "group":"Спортни","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/70787/2a00000152787b930baf817e916cede44461/160x160"},
  "Матч! Футбол 2 HD":{"id":"МАТЧ! Футбол 2", "group":"Спортни","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/28884/2a0000015278712fee31f63c0011536ae5a0/160x120"},
  "Матч! Футбол 3 HD":{"id":"МАТЧ! Футбол 3 (HD)", "group":"Спортни","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/70787/2a00000152787b6b8b999d50ae733ed745b6/160x120"},
  "Наш Футбол HD":{"id":"Наш Футбол HD", "group":"Спортни","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/28884/2a00000152365a12ea58fd1daa7ea78b64b3/z"},
  "Тест: Наш Футбол":{"id":"НТВ-ПЛЮС Наш Футбол", "group":"Спорт","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/28884/2a00000152365a12ea58fd1daa7ea78b64b3/z"},
  "Конный Мир HD":{"id":"Конный Мир", "group":"Спортни","logo":"http://avatars.mds.yandex.net/get-tv-channel-logos/55846/2a000001533cdd17887643d3fb857edbe0a6/z"},
  "Viasat Sport HD":{"id":"Viasat Sport HD", "group":"Спортни","logo":"http://vignette4.wikia.nocookie.net/logopedia/images/e/ef/FileViasat_sport_hd.png/revision/latest/scale-to-width-down/185"}, 
  ###Erotic
  "Private":{"id":"Private", "group":"Възрастни","logo":""},
  "Sexto Senso":{"id":"Sexto Senso", "group":"Възрастни","logo":""},
  "SCT Exotica":{"id":"SCT Exotica", "group":"Възрастни","logo":""},
  "TGirls":{"id":"TGirls", "group":"Възрастни","logo":""},
  "SCT Satisfaction":{"id":"SCT Satisfaction", "group":"Възрастни","logo":""},
  "Penthouse HD1":{"id":"Penthouse HD1", "group":"Възрастни","logo":""},
  "Hustler HD":{"id":"Hustler HD", "group":"Възрастни","logo":""},
  "Redlight HD":{"id":"Redlight HD", "group":"Възрастни","logo":""},
  "Dorcel HD":{"id":"Dorcel", "group":"Възрастни","logo":""},
  "EroX":{"id":"EroX", "group":"Възрастни","logo":""},
  "EroXX HD":{"id":"EroXX HD", "group":"Възрастни","logo":""},
  "Hustler TV":{"id":"Hustler", "group":"Възрастни","logo":""},
  "Brazzers TV":{"id":"Brazzers", "group":"Възрастни","logo":""},
  "Dusk!":{"id":"Dusk!", "group":"Възрастни","logo":""},
  "SuperOne":{"id":"SuperOne", "group":"Възрастни","logo":""},
  "Dorcel TV":{"id":"Dorcel", "group":"Възрастни","logo":""},
  "French Lover":{"id":"French Lover", "group":"Възрастни","logo":""},
  "Passion XXX":{"id":"Passion XXX", "group":"Възрастни","logo":""},
  "CentoCento":{"id":"CentoCento", "group":"Възрастни","logo":""},
  "SCT Teleitalia":{"id":"SCT Teleitalia", "group":"Възрастни","logo":""},
  "SCT Boy & Boy":{"id":"SCT Boy & Boy", "group":"Възрастни","logo":""},
  "XXL HD":{"id":"XXL HD", "group":"Възрастни","logo":""},
  "Pink Plus":{"id":"Pink Plus", "group":"Сръбски","logo":""},
  "Pink 2":{"id":"Pink 2", "group":"Сръбски","logo":""},
  "Pink 3":{"id":"Pink 3", "group":"Сръбски","logo":""},
  "Pink M":{"id":"Pink M", "group":"Сръбски","logo":""},
  "Pink Reality":{"id":"Pink Reality", "group":"Сръбски","logo":""},
  "Pink Film":{"id":"Pink Film", "group":"Сръбски","logo":""},
  "Pink Movies":{"id":"Pink Movies", "group":"Сръбски","logo":""},
  "Pink Premium":{"id":"Pink Premium", "group":"Сръбски","logo":""},
  "Pink Comedy":{"id":"Pink Comedy", "group":"Сръбски","logo":""},
  "Pink Thriller":{"id":"Pink Thriller", "group":"Сръбски","logo":""},
  "Pink Horror":{"id":"Pink Horror", "group":"Сръбски","logo":""},
  "Pink Rommance":{"id":"Pink Rommance", "group":"Сръбски","logo":""},
  "Pink Crime":{"id":"Pink Crime & Mystery", "group":"Сръбски","logo":""},
  "Pink Action":{"id":"Pink Action", "group":"Сръбски","logo":""},
  "Pink World":{"id":"Pink World", "group":"Сръбски","logo":""},
  "Pink Western":{"id":"Pink Western", "group":"Сръбски","logo":""},
  "Pink Sci-Fi":{"id":"Pink Sci Fi & Fantasy", "group":"Сръбски","logo":""},
  "Pink Soap":{"id":"Pink Soap", "group":"Сръбски","logo":""},
  "Pink Pedia":{"id":"Pink Pedia", "group":"Сръбски","logo":""},
  "Pink Kuvar":{"id":"Pink Kuvar", "group":"Сръбски","logo":""},
  "Pink Serie":{"id":"Pink Serie", "group":"Сръбски","logo":""},
  "Pink Extra":{"id":"Pink Extra", "group":"Сръбски","logo":""},
  "Pink Zabava":{"id":"Pink Zabava", "group":"Сръбски","logo":""},
  "Pink Folk":{"id":"Pink Folk 1", "group":"Сръбски","logo":""},
  "Pink Folk 2":{"id":"Pink Folk 2", "group":"Сръбски","logo":""},
  "Pink Music":{"id":"Pink Music", "group":"Сръбски","logo":""},
  "Pink Hits 2":{"id":"Pink Hits 2", "group":"Сръбски","logo":""},
  "Pink-N-Roll":{"id":"Pink&Roll", "group":"Сръбски","logo":""},
  "Pink":{"id":"Pink", "group":"Сръбски","logo":""},
  "Happy RS":{"id":"Happy RS", "group":"Сръбски","logo":""},
  "Prva RS":{"id":"Prva RS", "group":"Сръбски","logo":""},
  "РТС 1":{"id":"РТС 1", "group":"Сръбски","logo":""},
  "РТС 2":{"id":"РТС 2", "group":"Сръбски","logo":""},
  "РТС 3":{"id":"РТС 3", "group":"Сръбски","logo":""},
  "B92":{"id":"B92", "group":"Сръбски","logo":""},
  "Grand":{"id":"Grand", "group":"Сръбски","logo":""},
  "Grand 2":{"id":"Grand 2", "group":"Сръбски","logo":""},
  "Hayat Folk":{"id":"Hayat Folk", "group":"Сръбски","logo":""},
  "Hayat Music":{"id":"Hayat Music", "group":"Сръбски","logo":""},
  "Сител MK":{"id":"Сител MK", "group":"Сръбски","logo":""},
  "MRTV 1":{"id":"MRTV 1", "group":"Сръбски","logo":""},
  "MRTV 2":{"id":"MRTV 2", "group":"Сръбски","logo":""},
  "MRTV 3":{"id":"MRTV 3", "group":"Сръбски","logo":""},
  "Телма MK":{"id":"Телма MK", "group":"Сръбски","logo":""},
  "Алфа MK":{"id":"Алфа MK", "group":"Сръбски","logo":""},
  "Канал 5 MK":{"id":"Канал 5 MK", "group":"Сръбски","logo":""},
  "24 Вести MK":{"id":"24 Вести MK", "group":"Сръбски","logo":""},
  "Nova TV MK":{"id":"Nova TV MK", "group":"Сръбски","logo":""},
  "BNT1 +1":{"id":"BNT1 +1", "group":"Национални","logo":""},
  "BTV +1":{"id":"BTV +1", "group":"Национални","logo":""},
  "Nova +1":{"id":"Nova +1", "group":"Национални","logo":""},
  "BNT1 +2":{"id":"BNT1 +2", "group":"Национални","logo":""},
  "BTV +2":{"id":"BTV +2", "group":"Национални","logo":""},
  "Nova +2":{"id":"Nova +2", "group":"Национални","logo":""},
  "BNT1 +7":{"id":"BNT1 +7", "group":"Национални","logo":""},
  "BTV +7":{"id":"BTV +7", "group":"Национални","logo":""},
  "Nova +7":{"id":"Nova +7", "group":"Национални","logo":""},
  "BNT1 +24":{"id":"BNT1 +24", "group":"Национални","logo":""},
  "BTV +24":{"id":"BTV +24", "group":"Национални","logo":""},
  "Nova +24":{"id":"Nova +24", "group":"Национални","logo":""},
  "BNT1 +48":{"id":"BNT1 +48", "group":"Национални","logo":""},
  "BTV +48":{"id":"BTV +48", "group":"Национални","logo":""},
  "Nova +48":{"id":"Nova +48", "group":"Национални","logo":""},
  "BNT1 +1 LQ":{"id":"BNT1 +1 LQ", "group":"Национални","logo":""},
  "BTV +1 LQ":{"id":"BTV +1 LQ", "group":"Национални","logo":""},
  "Nova +1 LQ ":{"id":"Nova +1 LQ ", "group":"Национални","logo":""},
  "BNT1 +2 LQ":{"id":"BNT1 +2 LQ", "group":"Национални","logo":""},
  "BTV +2 LQ":{"id":"BTV +2 LQ", "group":"Национални","logo":""},
  "Nova +2 LQ":{"id":"Nova +2 LQ", "group":"Национални","logo":""},
  "BNT1 +7 LQ":{"id":"BNT1 +7 LQ", "group":"Национални","logo":""},
  "BTV +7 LQ":{"id":"BTV +7 LQ", "group":"Национални","logo":""},
  "Nova +7 LQ":{"id":"Nova +7 LQ", "group":"Национални","logo":""},
  "BNT1 +24 LQ":{"id":"BNT1 +24 LQ", "group":"Национални","logo":""},
  "BTV +24 LQ":{"id":"BTV +24 LQ", "group":"Национални","logo":""},
  "Nova +24 LQ":{"id":"Nova +24 LQ", "group":"Национални","logo":""},
  "BNT1 +48 LQ":{"id":"BNT1 +48 LQ", "group":"Национални","logo":""},
  "BTV +48 LQ":{"id":"BTV +48 LQ", "group":"Национални","logo":""},
  "Nova +48 LQ":{"id":"Nova +48 LQ", "group":"Национални","logo":""},
  #Radios
  "Дарик радио":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/darik-radio-online-280x280.jpg"},
  "Radio Focus":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-focus.jpg"},
  "Radio Nova":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-nova-logo.jpg"},
  "Hristo Botev BNR":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/bnr-hristo-botev.jpg"},
  "horizont":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/bnr-logo.jpg"},
  "Radio Varna":{"id":"radio_varna", "group":"Радио","logo":"http://luboslovie.bg/wp-content/uploads/2014/07/5265bnr_radio-varna.jpg"},
  "BG radio":{"id":"bgradio", "group":"Радио","logo":"http://bgradios.com/images/bgradio-logo-280x280.jpg"},
  "veronika":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-veronika-logo.jpg"},
  "vitosha":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-vitosha-logo-280x280.jpg"},
  "Radio Fresh":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-fresh-logo-280x280.jpg"},
  "Radio City":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-city-logo-280x280.jpg"},
  "nrj":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-energy-logo-280x280.jpg"},
  "Radio Family":{"id":"", "group":"Радио","logo":"http://www.radiofamily.bg/img/logo.svg"},
  "Radio 1":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-1-logo1.jpg"},
  "FM+":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/fm-radio-logo-280x280.jpg"},
  "Magic FM":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/magic-fm-logo.jpg"},
  "tangramegarock":{"id":"", "group":"Радио","logo":"http://bgradios.com/images/radio-tangra-logo.jpg"},
  "radio1rock":{"id":"", "group":"Радио","logo":"http://www.radio1rock.bg/themes/radio1rock/images/sharing/radio_default_banner.jpg"},
}